backend:
  image:
    repository: ghcr.io/23120091/customer
    tag: latest

  nameOverride: customer
  fullnameOverride: customer
  databaseName: customer
  ingress:
    enabled: false
  extraEnvFroms: []
  extraVolumes:
    - name: customer-application
      configMap:
        name: customer-application-configmap
  extraVolumeMounts:
    - name: customer-application
      mountPath: /opt/yas/customer
  extraApplicationConfigPaths:
    - /opt/yas/customer/customer-application.yaml
