apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali-server
  namespace: argocd
spec:
  project: yas
  sources:
    - repoURL: https://kiali.github.io/helm-charts
      chart: kiali-server
      targetRevision: 1.85.x
      helm:
          values: |
            auth:
              strategy: anonymous
            deployment:
              accessible_namespaces:
                - "**"
            external_services:
              prometheus:
                url: http://prometheus-dev-server.observability-dev:80
              grafana:
                enabled: true
                internal_url: http://grafana.observability:80/
                external_url: https://grafana.tthong.dev/
              tracing:
                enabled: true
                provider: tempo
                internal_url: http://tempo-dev.observability-dev:3200/
                external_url: https://grafana.tthong.dev/
                use_grpc: false
                tempo_config:
                  datasource_uid: Tempo-Dev
                  org_id: "1"
                  url_format: grafana
    - repoURL: https://github.com/23120091/yas
      targetRevision: main
      path: k8s/istio
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
