apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - {env: "dev",        namespace: "observability-dev",    syncWave: "-2", nodeSelector: "dev"}
          - {env: "staging",    namespace: "observability-staging", syncWave: "-2", nodeSelector: "staging"}
          - {env: "production", namespace: "observability-production", syncWave: "-2", nodeSelector: "production"}
  template:
    metadata:
      name: "prometheus-{{env}}"
      labels:
        env: "{{env}}"
        service: monitoring
      annotations:
        argocd.argoproj.io/sync-wave: "{{syncWave}}"
    spec:
      project: yas
      source:
        repoURL: https://github.com/23120091/yas
        targetRevision: main
        path: k8s/charts/monitoring
        helm:
          valueFiles:
            - "values.yaml"
            - "values-{{env}}.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true