backend: 
  image: 
    repository: ghcr.io/23120091/backoffice-bff
    tag: 0.5.1

  nameOverride: backoffice-bff
  fullnameOverride: backoffice-bff

  deployment:
    annotations:
      reloader.stakater.com/search: "true"
      configmap.reloader.stakater.com/reload: "yas-gateway-routes-config-configmap,storefront-bff-extra-configmap"

  ingress:
    enabled: true
    host: backoffice.tthong.dev
    path: /

  extraEnvs:
    - name: SPRING_PROFILES_ACTIVE
      value: k8s
    - name: UI_HOST
      value: http://backoffice-ui:3000


  extraVolumes:
    - name: yas-gateway-routes-config
      configMap:
        name: yas-gateway-routes-config-configmap
    - name: backoffice-bff-extra-config
      configMap:
        name: backoffice-bff-extra-configmap

  extraVolumeMounts:
    - name: yas-gateway-routes-config
      mountPath: /opt/yas/gateway-routes-config
    - name: backoffice-bff-extra-config
      mountPath: /opt/yas/extra-config
      
  extraApplicationConfigPaths:
    - /opt/yas/gateway-routes-config/gateway-routes-config.yaml
    - /opt/yas/extra-config/backoffice-bff-extra-config.yaml

  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      cpu: 1500m
      memory: 1536Mi

  autoscaling:
    enabled: false 

