backend:
  image:
    repository: ghcr.io/23120091/location
    tag: 0.4.1
  nameOverride: location
  fullnameOverride: location
  databaseName: location
  ingress:
    enabled: true
    host: api.yas.local
    path: /
  resources:
    requests:
      cpu: 50m
      memory: 1Gi
    limits:
      cpu: 3000m
      memory: 3Gi
  autoscaling:
    enabled: false 

