backend:
  image:
    repository: ghcr.io/23120091/media
    tag: 0.4.0

  nameOverride: media
  fullnameOverride: media
  databaseName: media
  ingress:
    enabled: true
    host: api.yas.local
    path: /media/
  extraVolumes:
    - name: media-application
      configMap:
        name: media-application-configmap
  extraVolumeMounts:
    - name: media-application
      mountPath: /opt/yas/media
  extraApplicationConfigPaths:
    - /opt/yas/media/media-application.yaml

  resources:
    requests:
      cpu: 500m      
      memory: 1Gi    
    limits:
      cpu: 3000m      
      memory: 3Gi

  autoscaling:
    enabled: false 
