backend:
  image:
    repository: ghcr.io/23120091/payment-paypal
    tag: 0.5.1
  nameOverride: payment-paypal
  fullnameOverride: payment-paypal
  databaseName: payment-paypal
  ingress:
    enabled: true
    host: api.yas.local
    path: /
  extraVolumes:
    - name: payment-paypal-application-config
      configMap:
        name: payment-paypal-application-configmap
  extraVolumeMounts:
    - name: payment-paypal-application-config
      mountPath: /opt/yas/payment-paypal
  extraApplicationConfigPaths:
    - /opt/yas/payment-paypal/payment-paypal-application.yaml
  resources:
    requests:
      cpu: 50m
      memory: 700Mi
    limits:
      memory: 768Mi
  autoscaling:
    enabled: false 

