backend:
  image:
    repository: ghcr.io/23120091/promotion
    tag: 0.4.1
  nameOverride: promotion
  fullnameOverride: promotion
  databaseName: promotion
  ingress:
    enabled: true
    host: api.yas.local
    path: /
  resources:
    requests:
      cpu: 50m
      memory: 900Mi
    limits:
      memory: 1.2Gi
  autoscaling:
    enabled: false 

