backend:
  image:
    repository: ghcr.io/23120091/rating
    tag: 0.4.1
  nameOverride: rating
  fullnameOverride: rating
  databaseName: rating
  ingress:
    enabled: true
    host: api.yas.local
    path: /
  resources:
    requests:
      cpu: 50m
      memory: 900Mi
    limits:
      memory: 1Gi
  autoscaling:
    enabled: false 

