backend:
  image:
    repository: ghcr.io/23120091/rating
    tag: latest
  nameOverride: rating
  fullnameOverride: rating
  databaseName: rating
  ingress:
    enabled: true
    host: api.yas.local
    path: /
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 3000m
      memory: 3Gi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 20
    targetCPUUtilizationPercentage: 60
