backend:
  image:
    repository: ghcr.io/23120091/recommendation
    tag: 0.4.0
  nameOverride: recommendation
  fullnameOverride: recommendation
  databaseName: recommendation
  ingress:
    enabled: true
    host: api.yas.local
    path: /
  extraEnvFroms:
    - secretRef:
        name: yas-openai-api-key-secret
  extraVolumes:
    - name: recommendation-application
      configMap:
        name: recommendation-application-configmap
  extraVolumeMounts:
    - name: recommendation-application
      mountPath: /opt/yas/recommendation
  extraApplicationConfigPaths:
    - /opt/yas/recommendation/recommendation-application.yaml
  resources:
    requests:
      cpu: 50m
      memory: 1Gi
    limits:
      cpu: 3000m
      memory: 3Gi
  autoscaling:
    enabled: false 

