backend:
  image:
    repository: ghcr.io/23120091/tax
    tag: 0.4.1
  nameOverride: tax
  fullnameOverride: tax
  databaseName: tax
  ingress:
    enabled: true
    host: api.yas.local
    path: /
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      memory: 1.1Gi
  autoscaling:
    enabled: false 

