name: {{SERVICE_NAME}}

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - "{{SERVICE_NAME}}/**"
      - ".github/workflows/shared-java-ci.yml"
      - ".github/workflows/{{SERVICE_NAME}}-ci.yaml"
      - "pom.xml"
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - "{{SERVICE_NAME}}/**"
      - ".github/workflows/shared-java-ci.yml"
      - ".github/workflows/{{SERVICE_NAME}}-ci.yaml"
      - "pom.xml"
  workflow_dispatch:

jobs:
  ci-cd:
    uses: ./.github/workflows/shared-java-ci.yml
    with:
      service_name: '{{SERVICE_NAME}}'
      service_path: '{{SERVICE_NAME}}'
      docker_image: 'ghcr.io/nashtech-garage/yas-{{SERVICE_NAME}}:latest'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}