grafana:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

  # Datasources — auto-provisioned on startup
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus-Dev
          uid: Prometheus-Dev
          type: prometheus
          url: http://prometheus-dev-server.observability-dev:80
          access: proxy
          isDefault: true
          editable: false
        - name: Prometheus-Staging
          uid: Prometheus-Staging
          type: prometheus
          url: http://prometheus-staging-server.observability-staging:80
          access: proxy
          editable: false
        - name: Prometheus-Production
          uid: Prometheus-Production
          type: prometheus
          url: http://prometheus-production-server.observability-production:80
          access: proxy
          editable: false
        - name: Loki-Dev
          uid: Loki-Dev
          type: loki
          url: http://loki-dev-read.observability-dev:3100
          access: proxy
          editable: false
        - name: Tempo-Dev
          uid: Tempo-Dev
          type: tempo
          url: http://tempo-dev.observability-dev:3200
          access: proxy
          editable: false
        - name: Loki-Staging
          uid: Loki-Staging
          type: loki
          url: http://loki-staging-read.observability-staging:3100
          access: proxy
          editable: false
        - name: Tempo-Staging
          uid: Tempo-Staging
          type: tempo
          url: http://tempo-staging.observability-staging:3200
          access: proxy
          editable: false
        - name: Loki-Production
          uid: Loki-Production
          type: loki
          url: http://loki-production-read.observability-production:3100
          access: proxy
          editable: false
        - name: Tempo-Production
          uid: Tempo-Production
          type: tempo
          url: http://tempo-production.observability-production:3200
          access: proxy
          editable: false

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
      folderAnnotation: grafana_folder

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: sidecarProvider
          orgId: 1
          folder: YAS
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/grafana

  ingress:
    enabled: true
    hosts:
      - "grafana.tthong.dev"

  admin:
    existingSecret: "grafana-admin-secret"
    userKey: "admin-user"     
    passwordKey: "admin-password" 

prometheus:
  enabled: false
  server:
    enabled: false
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  nodeExporter:
    enabled: false
