grafana:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

  # Datasources — auto-provisioned on startup
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus-Dev
          type: prometheus
          url: http://prometheus-dev-server.observability-dev:80
          access: proxy
          isDefault: true
          editable: false
        - name: Prometheus-Staging
          type: prometheus
          url: http://prometheus-staging-server.observability-staging:80
          access: proxy
          editable: false
        - name: Prometheus-Production
          type: prometheus
          url: http://prometheus-production-server.observability-production:80
          access: proxy
          editable: false
        - name: Loki-Dev
          type: loki
          url: http://loki-read.observability-dev:3100
          access: proxy
          editable: false
        - name: Tempo-Dev
          type: tempo
          url: http://tempo-dev.observability-dev:3200
          access: proxy
          editable: false
        - name: Loki-Staging
          type: loki
          url: http://loki-read.observability-staging:3100
          access: proxy
          editable: false
        - name: Tempo-Staging
          type: tempo
          url: http://tempo-staging.observability-staging:3200
          access: proxy
          editable: false
        - name: Loki-Production
          type: loki
          url: http://loki-read.observability-production:3100
          access: proxy
          editable: false
        - name: Tempo-Production
          type: tempo
          url: http://tempo-production.observability-production:3200
          access: proxy
          editable: false

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: YAS
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      infra-dev:
        file: dashboards/infra-dev.json
      infra-staging:
        file: dashboards/infra-staging.json
      infra-production:
        file: dashboards/infra-production.json
      red-dev:
        file: dashboards/red-dev.json
      red-staging:
        file: dashboards/red-staging.json
      red-production:
        file: dashboards/red-production.json
      jvm-dev:
        file: dashboards/jvm-dev.json
      jvm-staging:
        file: dashboards/jvm-staging.json
      jvm-production:
        file: dashboards/jvm-production.json
      app-dev:
        file: dashboards/app-dev.json
      app-staging:
        file: dashboards/app-staging.json
      app-production:
        file: dashboards/app-production.json

  ingress:
    enabled: true
    hosts:
      - "grafana.tthong.dev"

  admin:
    existingSecret: "grafana-admin-secret"
    userKey: "admin-user"     
    passwordKey: "admin-password" 

prometheus:
  enabled: false
  server:
    enabled: false
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  nodeExporter:
    enabled: false
