grafana:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

  # Datasources — auto-provisioned on startup
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus-Dev
          type: prometheus
          url: http://prometheus-dev-server.observability-dev:80
          access: proxy
          isDefault: true
          editable: false
        - name: Prometheus-Staging
          type: prometheus
          url: http://prometheus-staging-server.observability-staging:80
          access: proxy
          editable: false
        - name: Prometheus-Production
          type: prometheus
          url: http://prometheus-production-server.observability-production:80
          access: proxy
          editable: false
        - name: Loki-Dev
          type: loki
          url: http://loki-dev-gateway.observability-dev:80
          access: proxy
          editable: false
        - name: Tempo-Dev
          type: tempo
          url: http://tempo-dev.observability-dev:4318
          access: proxy
          editable: false
        - name: Loki-Staging
          type: loki
          url: http://loki-staging-gateway.observability-staging:80
          access: proxy
          editable: false
        - name: Tempo-Staging
          type: tempo
          url: http://tempo-staging.observability-staging:4318
          access: proxy
          editable: false
        - name: Loki-Production
          type: loki
          url: http://loki-production-gateway.observability-production:80
          access: proxy
          editable: false
        - name: Tempo-Production
          type: tempo
          url: http://tempo-production.observability-production:4318
          access: proxy
          editable: false

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: YAS
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      jvm-micrometer:
        gnetId: 4701
        revision: 9
      spring-boot:
        gnetId: 10280
        revision: 1

  ingress:
    enabled: true
    hosts:
      - "grafana.tthong.dev"

  admin:
    existingSecret: "grafana-admin-secret"
    userKey: "admin-user"     
    passwordKey: "admin-password" 

prometheus:
  enabled: false
  server:
    enabled: false
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  nodeExporter:
    enabled: false
