backend:
  image:
    repository: ghcr.io/23120091/search
    tag: latest

  nameOverride: search
  fullnameOverride: search
  databaseName: search
  ingress:
    enabled: false
  extraEnvFroms:
    - secretRef:
        name: yas-elasticsearch-credentials-secret
  extraEnvs:
    - name: ELASTICSEARCH_USERNAME
      valueFrom:
        secretKeyRef:
          name: yas-elasticsearch-credentials-secret
          key: username
    - name: ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: yas-elasticsearch-credentials-secret
          key: password
  extraVolumes:
    - name: search-application
      configMap:
        name: search-application-configmap
  extraVolumeMounts:
    - name: search-application
      mountPath: /opt/yas/search
  extraApplicationConfigPaths:
    - /opt/yas/search/search-application.yaml
