---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all-by-default
  namespace: dev
spec:
  {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-to-storefront-bff
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: storefront-bff
  rules:
    - to:
        - operation:
            ports: ["80"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-to-backoffice-bff
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backoffice-bff
  rules:
    - to:
        - operation:
            ports: ["80"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-bff-to-storefront-ui
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: storefront-ui
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/dev/sa/storefront-bff
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-bff-to-backoffice-ui
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backoffice-ui
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/dev/sa/backoffice-bff
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-bff-to-business-services
  namespace: dev
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - product
          - cart
          - order
          - customer
          - inventory
          - tax
          - media
          - search
          - rating
          - recommendation
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/dev/sa/storefront-bff
              - cluster.local/ns/dev/sa/backoffice-bff
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: product-allow-callers
  namespace: dev
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/dev/sa/storefront-bff
              - cluster.local/ns/dev/sa/backoffice-bff
              - cluster.local/ns/dev/sa/order
              - cluster.local/ns/dev/sa/search
              - cluster.local/ns/dev/sa/cart
              - cluster.local/ns/dev/sa/rating
              - cluster.local/ns/dev/sa/recommendation
              - cluster.local/ns/dev/sa/sampledata
              - cluster.local/ns/istio-system/sa/istiod
      to:
        - operation:
            methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
            paths: ["/*"]
  selector:
    matchLabels:
      app.kubernetes.io/name: product
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: product-allow-callers
  namespace: staging
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/staging/sa/storefront-bff
              - cluster.local/ns/staging/sa/backoffice-bff
              - cluster.local/ns/staging/sa/order
              - cluster.local/ns/staging/sa/search
              - cluster.local/ns/staging/sa/cart
              - cluster.local/ns/staging/sa/rating
              - cluster.local/ns/staging/sa/recommendation
              - cluster.local/ns/staging/sa/sampledata
              - cluster.local/ns/istio-system/sa/istiod
      to:
        - operation:
            methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
            paths: ["/*"]
  selector:
    matchLabels:
      app.kubernetes.io/name: product
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: product-allow-callers
  namespace: production
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/production/sa/storefront-bff
              - cluster.local/ns/production/sa/backoffice-bff
              - cluster.local/ns/production/sa/order
              - cluster.local/ns/production/sa/search
              - cluster.local/ns/production/sa/cart
              - cluster.local/ns/production/sa/rating
              - cluster.local/ns/production/sa/recommendation
              - cluster.local/ns/production/sa/sampledata
              - cluster.local/ns/istio-system/sa/istiod
      to:
        - operation:
            methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
            paths: ["/*"]
  selector:
    matchLabels:
      app.kubernetes.io/name: product
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: search-allow-callers
  namespace: dev
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/dev/sa/product
              - cluster.local/ns/dev/sa/storefront-bff
              - cluster.local/ns/dev/sa/backoffice-bff
              - cluster.local/ns/istio-system/sa/istiod
      to:
        - operation:
            methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
            paths: ["/*"]
  selector:
    matchLabels:
      app.kubernetes.io/instance: search-dev
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: search-allow-callers
  namespace: staging
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/staging/sa/product
              - cluster.local/ns/staging/sa/storefront-bff
              - cluster.local/ns/staging/sa/backoffice-bff
              - cluster.local/ns/istio-system/sa/istiod
      to:
        - operation:
            methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
            paths: ["/*"]
  selector:
    matchLabels:
      app.kubernetes.io/instance: search-staging
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: search-allow-callers
  namespace: production
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/production/sa/product
              - cluster.local/ns/production/sa/storefront-bff
              - cluster.local/ns/production/sa/backoffice-bff
              - cluster.local/ns/istio-system/sa/istiod
      to:
        - operation:
            methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
            paths: ["/*"]
  selector:
    matchLabels:
      app.kubernetes.io/instance: search-production
