apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all-by-default
  namespace: production
spec: {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-to-storefront-bff
  namespace: production
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: storefront-bff
  rules:
    - to:
        - operation:
            ports: ["80"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-to-backoffice-bff
  namespace: production
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backoffice-bff
  rules:
    - to:
        - operation:
            ports: ["80"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress-to-swagger-ui
  namespace: production
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: swagger-ui
  rules:
    - to:
        - operation:
            ports: ["8080"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-bff-to-storefront-ui
  namespace: production
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: storefront-ui
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/production/sa/storefront-bff
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-bff-to-backoffice-ui
  namespace: production
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: backoffice-ui
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/production/sa/backoffice-bff
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-bff-to-cart
  namespace: production
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cart
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/production/sa/storefront-bff
              - cluster.local/ns/production/sa/backoffice-bff
              - cluster.local/ns/production/sa/order
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-bff-to-customer
  namespace: production
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: customer
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/production/sa/storefront-bff
              - cluster.local/ns/production/sa/backoffice-bff
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-bff-to-inventory
  namespace: production
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/production/sa/storefront-bff
              - cluster.local/ns/production/sa/backoffice-bff
              - cluster.local/ns/production/sa/order
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-bff-to-media
  namespace: production
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: media
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/production/sa/storefront-bff
              - cluster.local/ns/production/sa/backoffice-bff
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-bff-to-order
  namespace: production
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: order
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/production/sa/storefront-bff
              - cluster.local/ns/production/sa/backoffice-bff
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-bff-to-payment
  namespace: production
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: payment
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/production/sa/storefront-bff
              - cluster.local/ns/production/sa/backoffice-bff
              - cluster.local/ns/production/sa/order
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-bff-to-tax
  namespace: production
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tax
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/production/sa/storefront-bff
              - cluster.local/ns/production/sa/backoffice-bff
              - cluster.local/ns/production/sa/order
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: product-allow-callers
  namespace: production
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: product
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/production/sa/storefront-bff
              - cluster.local/ns/production/sa/backoffice-bff
              - cluster.local/ns/production/sa/order
              - cluster.local/ns/production/sa/search
              - cluster.local/ns/production/sa/cart
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: search-allow-callers
  namespace: production
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: search
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/production/sa/product
              - cluster.local/ns/production/sa/storefront-bff
              - cluster.local/ns/production/sa/backoffice-bff
