---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: argocd
spec:
  encryptedData:
    admin-password: AgAU1V7jv79qMMG/MnH/dqyzvmerjVqaoMTkTChP8Z26Mh3LldQ7iZYPa26rJmIk6ZiFkvF8FqO8VNOJQHRy5aUydAbQfg1mHeGu4PLiH43w78xKYHnIQpyvph39XMeeVH8UShZ685GiIHFktnXsGEyEi/5AoagvMw4+wwsJsJP2A+KHInsBC2+MQlmkSaDWP3kLhIHAvLg8yGol4FniQEqds4yOIDB6zjga2YgdVeu8PF+quC7X0naCvSr0Q4AN4PDMaLmIl3HbM4h2ablNGEQICBhsb99NjV2WeRpKZ0XxFYbH/on85MD3ZK7KomKp92KzGx0fXUPu9IIOnkqnI1NiSMa57dqLXge+1MaMM6xNAml/I+a7XpZv/BRFxNsX4uRbpny5u7RMeDSamNvx9mk7i/hueeDIrqTwL+kC2ROrsS+HA/4uYqj8S7z5sg2ZfqoyQm528oYOuGbKo+HGlJsOgQ0ezRhCWDt9D4w70X1cI8v5PLEpVRm4DItd9tJbnvw7o6SVOz8HZqAMI/K5YRhDJt44p2yQGJe2diQhVV98Rbq0GWbkVQJ3ZAwxBAdBwDhU1/kGeKyoSc2aWzZc+i1xe2G7zx0w60gUtPMprdN+63W43W25Mtf1YMEza/5g/FZcy0FS1A2quZXPSObWYUl2uf8CApEBgoKBdxMTPUpo3E5FVVZR2n5X0AAaUNoxwJasbKTesQ==
    admin-user: AgCwo5Vp0npg4THVtEG1YNuEdJmJQlt33wg+jEKrypHw48Q8ygSXr/FuVes6jVc/28/LpvkEQ15nWDcwZTe0MytKrbc7WywMybq0bH6+kBok+987bMkGsTodD9MN/b1sQl+GHl/HZWK0KyjcwzORF4Qgdtlxrwug3pW7n5O8qsLXdJLXQEw7Yu6FChUZTl+6F08AaQsH0u2VffYLWZndx0uWpZ2NyM0Yv3BKmGMktLm/ESHvA00PkZAOVNpx/EZ5APkTpV3ALaU8PpeipRWenPrCtrv8daId8VygCEJt8HhZgeYmzGVlVVQ+/RW2K/mBJpOMPAEzqvr/LxJl4YGU8yan8hjITy3YMgaPgjKPRqBfbtPt9eMyIE9uNE+ZAOB35y3+VwLe1T3f8t9XDel7lbELC6RXc3K4XPe3ZNFBtFfrelwtO2P4VVf0FFQiQ0Qa0doBb2pR46UH0k5Xr8z604BzrJn03tEG6sekQngPDtnGI9hfygODqXsi5J9HPQKigtf56tb1PGXFB2//IU5DGu4pNP5zxA6j+JWAf4PbNLjAPyTelmnyVhYfyLQKhyX5rx5pxXmTgOnApuL/O4wPmCPn/4OhxcSmjTj0O3iVr1IaMzQxvOFrPHhl1npbVuwOLnYqJDO6bFPMh18jHdp6Q6I5rcaUvnGflNDr0vK7hgt3mX2LWKKQ/Uq2oIOfHDj2e1QQ/RbfHg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/scope: cluster-wide
      name: grafana-admin-secret
      namespace: argocd
    type: Opaque
    
