ui:
  nodeSelector:
    env: dev
  image:
    repository: ghcr.io/23120091/backoffice-ui
    tag: latest
  nameOverride: backoffice-ui
  fullnameOverride: backoffice-ui
  ingress:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 384Mi
