backend:
  image:
    repository: ghcr.io/23120091/cart
    tag: latest
  nameOverride: cart 
  fullnameOverride: cart
  databaseName: cart
  resources:
    requests:
      cpu: 50m
      memory: 384Mi
    limits:
      memory: 1Gi
  extraVolumes:
    - name: cart-application-config
      configMap:
        name: cart-application-configmap

  extraVolumeMounts:
    - name: cart-application-config
      mountPath: /opt/yas/cart

  extraApplicationConfigPaths:
    - /opt/yas/cart/cart-application.yaml  
