backend:

  image:
    repository: ghcr.io/23120091/location
    tag: latest

  nameOverride: location
  fullnameOverride: location

  databaseName: location

  resources:
    requests:
      cpu: 50m
      memory: 850Mi
    limits:
      memory: 1Gi
