backend:

  image:
    repository: ghcr.io/23120091/location
    tag: latest

  nameOverride: location
  fullnameOverride: location

  databaseName: location

  resources:
    requests:
      cpu: 160m
      memory: 725Mi
    limits:
      cpu: 300m
      memory: 1Gi
