backend:

  image:
    repository: ghcr.io/23120091/location
    tag: latest

  nameOverride: location
  fullnameOverride: location

  databaseName: location

  resources:
    requests:
      cpu: 120m
      memory: 555Mi
    limits:
      cpu: 200m
      memory: 655Mi
