backend:
  image:
    repository: ghcr.io/23120091/order
    tag: latest
  nameOverride: order
  fullnameOverride: order
  databaseName: order
  resources:
    requests:
      cpu: 100m
      memory: 400Mi
    limits:
      cpu: 400m
      memory: 650Mi