backend:

  image:
    repository: ghcr.io/23120091/payment
    tag: latest

  nameOverride: payment
  fullnameOverride: payment

  databaseName: payment

  resources:
    requests:
      cpu: 256m
      memory: 700Mi
    limits:
      cpu: 750m
      memory: 1.1Gi

  extraVolumes:
    - name: payment-application-config
      configMap:
        name: payment-application-configmap

  extraVolumeMounts:
    - name: payment-application-config
      mountPath: /opt/yas/payment

  extraApplicationConfigPaths:
    - /opt/yas/payment/payment-application.yaml
