backend:
  image:
    repository: ghcr.io/23120091/rating
    tag: latest
  nameOverride: rating
  fullnameOverride: rating
  databaseName: rating
  resources:
    requests:
      cpu: 50m
      memory: 900Mi
    limits:
      memory: 1Gi