backend:
  image:
    repository: ghcr.io/23120091/rating
    tag: latest
  nameOverride: rating
  fullnameOverride: rating
  databaseName: rating
  resources:
    requests:
      cpu: 100m
      memory: 400Mi
    limits:
      cpu: 600m
      memory: 1Gi