ui:
  nodeSelector:
    env: dev
  image:
    repository: ghcr.io/23120091/storefront-ui
    tag: latest
  nameOverride: storefront-ui
  fullnameOverride: storefront-ui
  extraEnvs:
    - name: API_BASE_PATH
      value: http://storefront-dev.tthong.dev/api
  ingress:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 384Mi
