backend:

  image:
    repository: ghcr.io/23120091/tax
    tag: latest

  nameOverride: tax
  fullnameOverride: tax

  databaseName: tax

  resources:
    requests:
      cpu: 50m
      memory: 850Mi
    limits:
      memory: 1.1Gi
