backend:
  image:
    repository: ghcr.io/23120091/webhook
    tag: latest
  nameOverride: webhook
  fullnameOverride: webhook
  databaseName: webhook
  resources:
    requests:
      cpu: 50m
      memory: 1Gi
    limits:
      memory: 768Mi
