# Pin shared operators to master (control-plane) node
nodeSelector:
  node-role.kubernetes.io/control-plane: "true"
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
