apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  bootstrapAdmin:
    user:
      secret: keycloak-credentials
  db:
    vendor: postgres
    usernameSecret:
      name: postgresql-credentials
      key: username
    passwordSecret:
      name: postgresql-credentials
      key: password
    host: {{ .Values.postgresql.host }}
    database: keycloak
    port: 5432
  http:
    httpEnabled: true
    httpPort: 80
  hostname:
    hostname: {{ .Values.hostname }}
    backchannelDynamic: {{ .Values.backchannelDynamic }}
    strict: false
  proxy:
    headers: xforwarded
  ingress:
    enabled: true
    className: traefik
  unsupported:
    podTemplate:
      spec:
        {{- if .Values.affinity }}
        affinity:
          {{- toYaml .Values.affinity | nindent 10 }}
        {{- end }}
        volumes:
          - name: yas-themes
            configMap:
              name: yas-themes-configmap
        containers:
          - name: keycloak
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                cpu: 1000m
                memory: 1Gi
            volumeMounts:
              - name: yas-themes
                mountPath: /opt/keycloak/providers
