---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql.credentials
  namespace: kafka-dev
spec:
  encryptedData:
    password: AgB3a/V6MIw9KnPOM5OIYoYg4oqi+E2jb0UONM+u5RXDseVQ+O7wouKZmD4OTAjBQeQwG+sPFPsdihVGUvux0SrEbUFdYQZ6uLPD6a9tXjQ7o5dkVs2FmMrqr6acu8TTBHW69qsYQRFdGAi+FfpZGAqWtq7z9dqFSQbdn1fkzdZejjmjLPKVLxLdFDDyiyTyA7+izZqVQaXEGvlWvALqysDEdwJCebXTdgnka7T4Lpn7OvMbrMJpQ5DQAijHg1aTwbLxjkNmkVw8w2BKOWkjEvIilGgLWfoQOeAJ2qQy4aTXAnMJuz5C4jP8DQhwc5wxs94rDjskRoqJ///FVf/FcfLDWfN2XRRBzRWbeheZAMuiFym4+p9DYuBXt8AoCoU88bJRCY4eqe8XU3LlUsfAWU+JfsZoUfPlAYHRyvUTR4m8ysyeRxg31nLxqy8j0tDDKFBm8cDwckD4cmguEzo4wjm4hqRnzF+uTJNrDmxuMuci0+YR0T36o2UMYkulFRg5MyqZm44VuV+hKA+kUbh8KdQrYshOnq0iAUXI+m6HtRGNNFrNyJduiH4W6rVgT+vmdCFUna1h9ctCI1LCUjPaKI5lN0z+a3XMUMQQKEe7M6I7nd8H/V08ADG4mQ+59QE94uAcjLedHtmQRXqSxLhZcOtHWa3+swEjxndRknWdbMhDXJTmZrxd1QTfYWWXPFZ26XstTYbLkQ==
    username: AgA0/M5k4VLcoO/09xhNHVLncXzPt3+G6l3MM1/lb2ccd8+4orQQtQ9iTO58AdZQ5HU2hU8nVFToBrVn8lNDD9EIFDlKWGl9Avhq3u+McO7mPg+/eiU6xOdhbcvCRKyxJKsl2Euri9hY3qs7ct0Ty+PG0HJRiAv1lIsuS1PiSFl4c2kkIb0Qdw9VwgBQtIq7Of3Y9lI9qOgK3jEuJ/MtW1j4q8t73LsLUwP9691o4THTdtrNxxfNTuF4Ak4ukNsXWWHuexQffPC3RkY3AYx30miLAwGfoaZU1K/TZNzFoKQ2Ztl9b016S+libQ2HfOOwqBk974oKYrQlqHGRtxKqEBa/0XYulya/NOI8b3YhJHK17CCL1I6WjX82fnpR/CC0wkGoHsoJVLt+VQ7aybH2/b2gLiUtyo1FS+S3zS5xOZwK+o/T+GT9CnvyeI1Kb2zttt4gIlnzUsGSVwT6KJD5tx/3trnXwYoqL15P+Xl8LN5qliTeMAaYDyn4CfD81g7eUWIlKkX7zZCSy2GKDMIdppJP0cnycoHX/dhc0Hva6f77P3r4WdNCVxqLqMOyFjU3eZHMW31ZWGSBUZvXtHw6efoOqUvnbKPujAFktD33VeMt+6B6LSb8XLQUOWKOSVDk4yEbTnW53CrP/R1W6bvk1iEG4NpHqmcGwjB560kEwHQNxhSIAzf8W9wDPr5Sgpzd0d9JdiUNpZZpBdNkaeM=
  template:
    metadata:
      name: postgresql.credentials
      namespace: kafka-dev
