---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql.credentials
  namespace: kafka-dev
spec:
  encryptedData:
    password: AgCRoDvNMCv+BRP0oJkLmTmfu8bkAcbfza30QuIfJYbD4CVUAS716BouXgBbRuo8vksZBHM/5s0qkzsDJZhZc/8MZy/Sj0E65+zxa9kX2wLG7KA4wbXA+vSnuEHNqGcWt5kdnWR9VQI18rbBuhc8S3P+neUM5CrhxuFW8XbaW5ZYXK2iqLYAh9Z3RkP9o0C/ZXyT4qqv/QxjGJwqcgqcffpgvtbIO/BP2dkSkWxhMw8x3oa+WfIn4nrrcYcRgESuBElK6u3vsCo62cFFFEKahbcgC670ekrlpN5rHGnCb/VQI8nwFqPm8C4FLDh/aAAsry46FXA4JIPQeaA3BIedWGAs91q1GbyJXpO5BsbA+vOM5uE19wHKK6quRrYsEXdwJEDWzmiVvUSf5kPPGhkEsWm+P1tQ7r/NL4LpqTxE70ZQ/NGMnABnbelbMcltXg/2PUQ73VlIHsG+rGsjKoZcEoQ1jV+ym15I6sVs1mEtuwlkMF+aRfLnGx8elt64L7ELglz4d9y+SZP1i0jMSt3tQcUfgsynswAHCNI1dkeYejvOkZUO/UTMglW0+atiursSOOf4iCIDRjYheyBmyKt20T+C79WqGH0ivttS1sGxUzDj7kuf/ir2zEI8+lGtZ4X6pE9tfWqoPO0h7s+AWltC1UCQzx36pBsMJNCy2UayiQ2ZUr5mVxexDtWtmhmcaCUHgKADKzs+kbdZ0FfCvwMa4DtC56HN435e4JXPprCfI2DaWMLQbMJGbGORd5M8KDc46Rl3TzndWbq/3Bu7Q+3kzOv2
    username: AgAHbuQAqkYmzt/80MCOLFTO/LXrFmFgVtmsGf541DccUNIgBhdzZiQjjA4cvXwku580ypaU/doFw3dmfZB8e5b4SjNOZs3KV7VxN8w9Ir3r3SKAR9gxQYL3AQ0K46xYXeU2TwdlHs+ywgho7gwrn2LAemOvx8WsGqjJXtM6pbJ4ldUKyhAygR0hgcTfbITQOeoQ32yW8kjHKcuXa7vnbWaIq9ntBswhjXX/ypEtKt5nzmgWVheaXXmh1AhdIwqQJgCjWBTZzSdb+wLq/xv6mCfGBd+eNmp6L0qn5qTePO1OT/umVPq+J/18XPW736elYiHsEWK/6ZZGDOTvTG4H7QawhBfY1EgEfTME60Ycns03wK8MsB6NO6Afxhy/9w13lxK7C370JRTcU/rZziDhq2HPt21IC06PATG6IvzI/8PVEspQjNOLgsgOAiILUTAGt/C8cymBLDbArY/2W3HjzHcbzNDMoCeqS6yD26vcmcr8hmm9TPh4VRt7OoaSG71R5yh1WLGMZctscRorU7St8zuzaVqLfZBsyWeVF7V+ZcjHUvRCswz0l7yex+Nn4o/y/Zhhmf5sOdqJsFBqa2smLa9iVUwUqAFbuAALWPiW9CTZBCdS/Q2E48p8eBbUI3x9JkwR0TGdHO5uQERISx27WnoOS7Cdz55XhAW5rYWjbtAAEhnHh0XNTCFe21VfY95h7FGugTvYGwQR5xcS4zw=
  template:
    metadata:
      name: postgresql.credentials
      namespace: kafka-dev
