---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql.credentials
  namespace: kafka-dev
spec:
  encryptedData:
    password: AgCZi7tJgv6us5uXPtUACdErspSddofO5gR8nZj8rdZeK2sWJU9WgOlTZkWGeeqLzzzyd6RvwGEGmqCAZVhN1GQcLqNzvK/5isFZqnjS2D7U3alH5b89jQYGL9OaQri4qlv8nqcExIzjxh5OfhPyfwWd6uwBFvhemxkSu6BzHbUTNx56+b5eSo+YT3VO1thrlsVRaILzOE6Tyi3YW13371aY0IFAsY0pPBsvzfTJFwMN2jvZAaDVyeTzNrijGAnygdLhXLMmr0vsxIVoSEEzdjeowZm1mxUOPDRdVBmm0/txY0Np28CzG5fEWycK2VOBC32HZg8Hpp4fHz2zFm9fGEIS6zH5/REzn8ftCiUKpLiqnPRJi7zT8kgQYMTVq1gSu0ckglIZiOVktRKMnfIe0kk50qZx5u70sBbYac6CmWPTL4Zbf7bO0qer+3HtYJY2B5Y6iWCu5Oyqm4HpthybDggJHoNXUjGkasPmGlGJ3vqRS4gYEq+RqAR8BC8nXyDsyL0mrk7AF8n+xHmQZXAaSp+dkgX4DasDZEOPI6l5yvjYSuCWDXtG5zMscMejbVixFOvvPkwjyYFf42dYegOYUgyNuivMWlnvHH4rW6NDB9CiY5ElGM2Sg1EcuAzVYCEBPnYw5mlXOuFgAOWrsfu0YHiLM0odW5dMF5QIphIwXIo71QW18zaPjPtHl0RMmmmMPhLhNzDCGg==
    username: AgCsFWu8Oe309f0Va4IKHChdKXFATnjiNJ9rP89zaqWvAXljm3wmR+7s9OnJRqHpc5ftKRsPatv1t+BSD8X25Wu0Cqpshef/94zjR40nBX6Cxc2V5h04a8ggnT2s08RqxpKml1Jrr7F0NnoRkDbghyM+N7k8eFOGRvlSR2Fny1z7QL3uDsDItePkgdjtoE2R7A3lBNmLw7ieXFvrgOk/CCVZEvBVyNTWUcy8MO+G9jKkwt/C1xtATpHmhi9majKfsz4QWbMyo4cntJ6U0wK69Fh1B8dsRl1bIHeh7jNzc3fICfHjUGbMkEurugq8RiE9joOlnr6hR0+0QCgw5ELggxdc23PxmCuyUQEBcLtKLggK0ISaDPjgYCmwrKjZSmwMG4Qb0FSWH0o5P/M9rbFK58DpomtLBjUQK1Zufe8rL6OalAgZ/nu/6oPyuGf0wJVzUim2fGcN6GKUZbTdxOzzrWDduoFmNiitZA4OWIU1qM1czHSxEgKXpigYeBt20dU1dILsLbEUvdkMWBLBWsc1Z/VSSVuwfydKi/op/TazT60GALa+FZVuQBXN3rBKhH6n3Ut0245k6vQlgGdJCzG6hvtkHC6qJYwFcZ5kSxBlO3/zvrU0AH2ny3GtwYBq1bSTvBUXR3Ab5q7RWSA/NgaO0+RbJLSuVbPqTISqa3gmj5V5clK//vubZMU8p/8k7kizMhLVXTNqkHJXPmkngd8=
  template:
    metadata:
      name: postgresql.credentials
      namespace: kafka-dev
