---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql.credentials
  namespace: kafka-production
spec:
  encryptedData:
    password: AgCmJnN3+Myf6Iazc7J3epuuf2jtTqCxbjvBgHxEt7Vz84RC9C1VyUrtBt2QXQ9gs+iIny2njZlCWsTs+tX9i8CTvziqPc5XXwQyVepYg1QlfF2NQasEXmUz6qgBQCBxOwglVqoFpqMKUpQU6ounLlRxxnp/i8ihYZ3NdDUX/wzATHg0uGgQMTHpXZItJrvNXCCJyzv7ivTxBF0lWbFRUblt2An8LfKo0rB601jvd2x4KaXvfrLo0jE+BH30Eqc6QG6FPrRmZefaTgrnRghjAifqA9HP3w02kbOWA98AzWLOvabnyLfDOX7VPAl15bJBEbII5qb+TYrMjEqQl20eJCNuLUg74GrkLymEsz+X4HT0V88xrz+SfFfRHgmfqzfZjsVlHvimBkjxpk91l/Zzr8hbsUrHgGiQ0BG94Q8y4/0aylE9Rp1vyx7VFRSqhutj0g1AOyogDnTZjJBOnwmQhWzZoMr9FsdiRcPgHTnd5OTgA5V+qD3+9vQ2MlJS1DbP9N68u9th5BeiQY/+110IJQ6w4S/ocXB1M4YU1Ib/OCb7OKgJ7XEILlIg2+RvuJ8JzOvydR4E8G6Z7o6P6LsI1iSkoYCmZrldMXxtpdz6q7CnsBPk1vZ5w+sRWYm68RL8ATfEQ5A6IBhwfeJPmogyrduSvttGYcNOy4jwd4BFiO8zorkOek8c9SzU9U+rBb5ek5GZhdpCosgiJ41Q7x9/BRO/so88jBIWeotzNGpkoWTqrQbp64yfmxiLst3zq6DFUkZuZzDmudV7V2gKjaTABMHi
    username: AgABRHNLBzU6M+3mNUgZxwITpElZXl4NJNJKYEJr+4452xsqJtZlxaKg0LuI+rg0lf3qgp9hR8wE5H7eBYc9LUE1PtGKUX4zHzBs6W+14d9/DJCRdmw8GF2H0Xjc+x6BUc6cG9eXSdrRii0Pzq03p/j9PQLO0aw3LF94sK2V1zhCNX197cvh5K+LuNyBCxEO4gG4ATu+Wm5zEKps0lqE0J6FLpUiMWHc09iL4pzUlOQajaaAOOirhyFplv41sxW5zJbLhMbrHAXsOvdRc+IisK27ly6WBQx15/h+Yh/CsEIRXcLsoldL6OPJZTIvZQPpcrBKrktR8938LFRwhu+YVNLY448hYAWEjCqAfBXXbHEH4++nBLsE2Rua6QVnL+nt7qc/BBcF8K8ZGjB6D42Njak5lO7/D3L1SpYNudPQmdf9cbeN6vn7jRLqFWDdvLywEvE3EznSSe4wdAqw/FrhXpaIp84kQhrfAvSAg2NQKa5lXWBZXGaf1wB5uch+OxnQngZVgD5sbgJqtngJ89wo0YkmMHOYwI2IQjbUGOcrXOTE4adrGcxSlEJ2SpgEknxu24SglAK0CpuLbLkQ0mn/3++mVk/B54znzJdyDHj2lKFn1kkRpJN3wg1gBvB0IOfPD+uk0DKPQu3d0PwKiHjHnNMtXwa2jvESdfpfNbhnGG0WIxmUdcOYOUjFHGqOzEUOiAQcjCaiqdUYqN7p5Ww=
  template:
    metadata:
      name: postgresql.credentials
      namespace: kafka-production
