---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql.credentials
  namespace: kafka-production
spec:
  encryptedData:
    password: AgBBJdJrJjWxos3ePV2PgY5wU+OPeztJ1G7D9WTqKxCELHe/KD/Buq8He9eX3rGk634qqey9s93COpwKhEl5P3pPUIGL++xYQ9U2wj/azbfJq2iUgiVj1nsXxrr1iM8sF5wxteEJTEmti1gXzglIm9SRmMkHCSDsNSoIxK88WHa6VcPEwQ0l1Shz6IWw8RV7HQ3/FDE1xKThMTaGUaAQSVYb4NtclEofbcmIQLxqcuLfqFURjmsQiMMqN5EJEVy5g4oXrj6KA7jbKZ+Amid/9GpPpOn9+qEcvyVUZOl3xDTiL2OZ2DuOemIJtOVmJUTUFIlyFpolLr5zs2xBe3QX1SjxJcNz7ZbZ7P4H7QTSOlqkz2IvcfFRpDPv36T3Jm/ShsQdLW52S40NzbLhZBD3dA5PYZ+jdCj5XncETasS7LmCQL97YMCzzHT3oyywELj4Wv9HMJsISlgsR6hPcvku7aVmfzfKSAnCWF//5b2ENwDFNU+fVqkldji4513S412GvmP0+41Glli14rzl1KgaaXJmCcTGqpHtK+ZKkkIyuHoqHjHiuzct3ZXneP99aQ7N4bwXZWxsOXxZ8aseZsAv/A9ZtXDZza1jXqz+dTlgEWFFVLQRZz2X1ZSeRhFk+3AXXpsDbDpn0u5CJYXfSe1chPHGwOQDF0XR5WGUqyxoejwvQn1ZxvcklwgfqlyOtdNbvp6E4b9fjg==
    username: AgCrMgpFVrnVfVmlWsj/Te3NOkbolyvCROFjD3oL6ExMhPOvhBqVS9mprEo8aM0SprCMYM8QLpkiLQjMGRe7Xv38aZdhflwYb8dc+Dt1ladyQj4gSBSIWa9t7Mw3nGrhSG1qq0dqSPTYFxyQp5EYcf3aFZ1EKXAP4fHSYKSEDzsDz4nY+nrff7kQJfnE8DY3VJmmM3+i79EBIhxMszU4A/j8vL9RgqaLrXQLW8HLo7WAOicKYsBPo5YFaEO43L/0Wod8qC50odRzxIY/Ntw7Jzk5b7BJoG2YSM5aKr8DzGSqa0rElH4DSx0Wkwk8L0IDlc1Xi2hCmFmC1IAKHZ09XPTLIL0lGKatKXseb7ZYA09e94TYwtd8PRO7GEOOrm0ufw1xh61G2jeMsnzx5+Obg+qLzUYF5xHk+zeSGEPZJD1WePb6bYJ9CFrkDvecII4NMLnsBeR9mJEjTLzGoihh3h8PJyqwiyw/52AyW8UNLWV1sbv13BDVG1tRJI1VGrz+WDr9Rc6t35xOTRf1L0cM2+4L5EzC41E7cwqpsM/f+nAzNcE0huTssTlvP10JV0m7J2WXkjWKSjbIjpdtc/zjF4iYE9BMhXYHKQsdsiCUN2hfmBmIPADFcEJeBwUkK2dPs1+2v1nbF7WLgEtS2uirSKEUEgP5VBWxXR396ADvJmq97UTgZKdAHkD/6LfL7hhJu8YzRg9i/JrJ/DE5jaU=
  template:
    metadata:
      name: postgresql.credentials
      namespace: kafka-production
