---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql.credentials
  namespace: kafka-production
spec:
  encryptedData:
    password: AgB0yLWGIALkb+zRcEuHTul02Jcmo94yq2mfOfbiidkVFg4jAceMnpe3E4DWacjPzFnb8qSsbH8Y5XaRKwVcd9IMzFmB2sLhHJ9SuIBnBkGY9bDVK9Fg5tOqKsX6exCrU0ZIE0shFHsBxyqFw4h8UbMbYlTxlJsevlKFBEwX5N1vfV6TC4szRA96zjh9wjYhxzoBg0CPRGFtAj0Z/D7Jrg4ahjgfX9NCdcXt5qmZ0HuyxlgepZqUGu+PrFBc6I5MPLDp2h3EZ0nvZwtcWKShQ8Nu2vEzg9jXYaV2O4x9Ol0nl3fdc2cTVv44R8p2GUCPMDAGAHeNRtC2ufrjtYqZU1ZtXIeHXfm65gTZ2oaD8UJgaC5+43p4nIloOPk0AbgGqaXvjDHYiLu3hsAyMsEAGveKFOM0oQ39icqvX4CmvXRkNaNBjgZyYW8t6GOdxS8HQxbDT5/Nw3AccuGX/we+zUFNbed1RaVExolDSVZEsQ+a0PgedoptkKuferYxRHNUu5/HtbKfa6LugkFAX6Jn0Laugiy0iKOAKTo8Q1gvEUSNWdJOCRkidK0sUKWjiKckfezOqSGP8qyzIYb/eNjHX9OTPCkhk06LTrLpTyCif2evrBCnR7widcGRHrTk2d0MXDaRfm/abDZZgAhk/tQYaSNbcA9zUr5v+hd1hSrYFt+7jizwM2gEg9hLS3K7JFjqxLsjow2+D7BslFVOv+XF9n4ID0nxG6BrE2+Ndyn0ivz1PrOD1pwOToZ8JsslxzeXio/ZFGmMRCkP7V3Xln2/Cuym
    username: AgBnij/nO2DTr+BSSv2CsM5TkWVInwtvLr+m9LfTr8JtJzZiRoqabZKKAj7CShL67BjFfogd2rVQ9tKeNB3gSjtMya86gAkWUf/a/nubyqDk9aB31rMrpzfO3k6rLZAlxNR7/TmvRUgEei9TUu7ORnuDTJ1l8rzmcSzctwNM6EYxTzePEEfGMdBkBrj6EFvJgRklRzZ/6pEm8V2+x2lJz/0ERu8//iiq+GkGbk638V1eSo8lMdOaViVtEBs2nFPaL16UX0Ndx47QJvKsi2aIm/AWEhN/5jdZQSHz+bEzHQtw0yghldCxnqwQkBV09q8gI/YxZsOmTnzoeSXDtWoFrT5RTMsbGiPghCIpV+L38/lPrJV1KBOSgJK11e5Oi/59eqlcWH70+h3PzbHreWrmxaUFjwz9XqUoMQQhZaDKkFyd/yMCkGRkfZyx3/o/sgF3YzwAeKrZP6skSBXDS7LIIQobRMj3yBF33Fz1+949VvtVOfTf1S6mNflC9ZSUnC16h6rqXxWfwpuuH5jDzJQkEXBTBZ6EEMS1G7D+oTfW2YqoZXaPhTuUvhCqEtLzNdqUHLcDcJRF0J4Cwc41igh/XbJLIdIHeDbwVuSjlJVM7o03/LRngVkuJ148zwi6Lv2aO9lzOTEyVF7zDOcruRctpRp12swVFiWzplyX2dV0ecdzolngcOF5q4QR1YlylKVlOjB5l2bV4ldKdGsMjaI=
  template:
    metadata:
      name: postgresql.credentials
      namespace: kafka-production
