backend:
  image:
    repository: ghcr.io/23120091/recommendation
    tag: latest

  nameOverride: recommendation
  fullnameOverride: recommendation
  databaseName: recommendation
  ingress:
    enabled: false
  extraEnvFroms: []
  extraVolumes:
    - name: recommendation-application
      configMap:
        name: recommendation-application-configmap
  extraVolumeMounts:
    - name: recommendation-application
      mountPath: /opt/yas/recommendation
  extraApplicationConfigPaths:
    - /opt/yas/recommendation/recommendation-application.yaml
