apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: debezium-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap:9092
  groupId: connect-cluster
  configStorageTopic: kafka_connect_configs
  statusStorageTopic: kafka_connect_status
  offsetStorageTopic: kafka_connect_offsets
  image: {{ .Values.debeziumConnect.image }}
  config:
    plugin.path: /kafka/connect
    config.providers: secrets
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  template:
    pod:
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
    connectContainer:
      env:
        - name: ADVERTISED_HOSTNAME
          value: debezium-connect-cluster-connect-0.debezium-connect-cluster-connect.{{ .Release.Namespace }}.svc.cluster.local
  {{- if eq .Values.debeziumConnect.buildImage true }}
  build:
    output:
      type: docker
      image: {{ .Values.debeziumConnect.image }}
      pushSecret: {{ .Values.debeziumConnect.build.pushSecret }}
    plugins:
      - name: debezium-postgresql-connector
        artifacts:
          - type: tgz
            url: {{ .Values.debeziumConnect.build.pluginUrl }}
  {{- end }}
