---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: user-credentials-secret
  namespace: elasticsearch-production
spec:
  encryptedData:
    users: AgCfCSE5P0TIckruxy9ZcWASvTrCT52mp7yPadE65wnstw2v9UiCYRsyB10DKHoejRY+qMmhJllFZtDQqq9C4/PqGmnmgzCqfHy9LfQPW7paMgTa8aIcp6UYjMcaVJ32f9l4FjnhNtmytB1uqecXfrFhHT0e99x1PNia8LSyvLT47LO/hZnh1Ici2Y+BwJFJg6kzyaSfLPdhS35qDX2Z4ah+6agGieeVR16Z/aOzGoknN9J9Pasr1uCeMmNlL99g5aGbJ6Q/d5izdRTKXr2ugSvYYVZG+olJY0rCssaH/rCKu2J911OrHXF4qAYBqAkvu62ReSj+SuTIfy4RZ2FFCYx+Kd08KgZ5O0vz+4eM0QeY6L83youBgBhnnqAsUlfoyQoIJsH7YuN48tzrKnHn5jK4QmepZbB30npo76QbAnsETW6SSEKD80rS88mZqgENQPVkTLPz+mW+g/FkhMuKsPyJmWPuTPfwz6TA+6j9DApnGViVfQf9vkti3ey0AEEX7gHjZeMcWTDZEqjQPhTMo75nDAd8P+pFcL8lF9CeD+Lbj+3D4cDimksB1gnZyBJ2jITOgoLWAUlb6HXMcTUyl3Vh1OR+T+u9hkipVH6+mYUTvlRIyxUevkkIQSMVWMjMM08HT9lMydQn0FSOh6+bMIepWOL0GOcs7YUZ5mi5I+Gy1kWXD9l29pfrCE6iHnErePfzdSOo0eIZoxRpt+f62f7Pp4MUDNe5dnWZT21iEXWlag8lXGuClRrGhKccJNaoeNIZclF3kcAoMWGZ4bGTJNOB6nWwalmWZMLsbDzX0CTCpA3Gfgck7KM4nYVyao+iusUvc+79sp++I4k+AzuRf1las6pK37AktjMBrwqhoEJ1r0YLz7s=
    users_roles: AgBSFPVEbNmudsEAu7ko8gCqyWNv0EC6SNJY7oafmQJjX2JkXHHBnGu46PkAJYpMzp0iU8zC5sie9ZMb2Qqm2lKMcrTBLRJUuAkopHiVgSIGEqpWu/MZzuSrgxg7T+mBO1OqCqjbVh3mcvBN2AhEhghZEFg5WJIJZ6H/wWjhpo9iPB20MbEo0Wb0OregJE5+duQuPLAOsHfO3Xq7mQ0wyVyFq83BM8xbpSVx/wonPhjAbMOMaNKfVim3WJhmFRmqbUztcXYH9doa3MKp74Nc3oeeFEkKuJtHq46BWmPMmj5EK+ywdu4dMI2I6icYRREbn+FU1YmvCGYfgSohPgUupVVoKC+TGxjQ2CYsrvDYLGPbWMAEsJKSyJKVNSJOLR+s6/D2l6LQQVmm97mEW7P85JUYGNxkfQVlQQaNf+VuzuQRm4aIHNreZiZVAZ+wd4QdPsuS1uv00lah3imwJ1xRcIaAj77Djm1dbBvTDTW8bABg/1pGQXg4Mcmu6yJQjtBG+lcPE/6BgrrzsxvFFGBD66NPbrCU7Sdp/getUOCelB8UpuD31N5OLbqeT2xPRjgjmRM/PUEBui3gTgcksc17RU1pv7IfBDTeXlXtxsmIUgXOE2rO17cU8uvPt5l3UfcdNHjvMiebyOZ9eyTQqxBYsca/75z712u3kvRbVblALBodO0DH0artiE+TYfKqvgx5Qr6RAWvFDO85kZaOWNlFBI9g7ZwcfDGzlJNmRrvZWOU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: user-credentials-secret
      namespace: elasticsearch-production
    type: Opaque
