---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: keycloak-production
spec:
  encryptedData:
    password: AgBexnk+Exuik+6GpK2OlOGw8DoqU+flf0++NgusG/1Jhj3SOGfVvo0mJngfIK1HHimzsl/cVug0DLW/cz5lPl3n0UBf6fpLuO42jVLg//Bgz4rICdKLbqFQR5owXMGABId/fReIITlj3CwLCgY1ppJwNgsWpwRRIwJbwla5CIHToVHHmo5ycnNaRkoF0k/ZQNCwoI/aVPd0biMMiHGHIRS7nfOpGg0O7gk5K7E61o8TT+j7NDofRyGnUZ1Fe5uTNXtE+KoR3Rwj4RLw1Y4AmKbSSTP53wdXERFv8OxudqL90MbVJbkXc+KbWo17WdFH0bLqXRe/YqGtsRzhLwL1wke090Q/eNSyb1xyu7owbLK/R7XKSJKCiEzJV7eZS+Szvw4hwE3wUXJNO0qeSo314Hx0R0izEAxGMGZnp5PxPbB3PBmGUVgeIwg/v1IzFc/2Hh4mlDNqUBEtic/W7O2vKAG13iQF+u2yJuTYtG657QyOTmKO9V79lR+SX5JX9pCytpnkX1jOeujWkQJUy84HygsplGk/r2q4xO1ItA/L09LwjStu2Xkn+HvI9PHulOddMwgZbWmSPjExjdf/+1R4ZfKEC1NxWFuK4PrZls3YTVSlVJsbh8zlz5suhUCDTSa6RG71b+yq6BTDgLKqtgFb8XEziUXEfUZ1JlboiYRjO9xEmxJZ9tbwKu1PovXkAU9n8NvsGEJhs5A7Go1aCPmWST8JjP0EvCnjCmiqQAFEAkTYQ0gDuyOnmve1PYWtkJ/FnUBUh1cL4Wnxw6oyRFpu8BF1
    username: AgBX2BZhUJ6t2aMyJ0TcXEG7jvbVhtulVmQnjypSBgee2cemB5DbI0/K/zOppgCDdUwtU7GAMDBJaoI2dFWAjsTc7K0IfezqBR9hGNoY+BEWwpa+iMlYPPVnV8cblOZACNjtsvmyIaSQB2aM3kqdBvgUHAl9mGhivzXXE1Sg6pphxJVDikPyIDcbugYnICYnJJzclTEgJhdTn7yBurT/dwTxKmGG4vrWEVYJ/iF+IpdfXhuS1Lmatk0NnzcZ/bHUqi+Cs6RwevdCQ1rTehizX2Bt6+K14J0sVkbHK6rYJnfv0qA3hAKNyqvf0O8VlWVMrcAnkySLAORS9TYMr41cuH7Y6SBU50oduigUf4qZZpQZAiLJCjnm8H45zawUsXOIBRJrqZMyNu4TW7KUINPmMKVNZJ/nsU9qwziRjau8MdKvAt2g6Edzof0azdKzShoOxaJ1ydvy/pWcYyRcWYC9UbVOgs3wyMi6DBaHIXC9BVy51WplOvCB/0V7INFE0N+cM4wB5aIVBI28eRAjAAagsxo3xrMYb+yTLwFETz4tIHRs4xQfpjXkbUqJUpWrSoJIApyRjDJ1m82MkCyD73zyeFd2hrZaPbBVMuvON82I5ENpSsVkkUGzJcC4urf0OP3xciWthCHCq2zoIt3hab2pxYzWilrN92Cr0y4LPhuwlPx0MDRLzVMONB3KvXoY/p4k23ou7/ajE6HNTD9xh3o=
  template:
    metadata:
      name: postgresql-credentials
      namespace: keycloak-production
