---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-credentials
  namespace: keycloak-production
spec:
  encryptedData:
    password: AgCZ1j1Lm4vtJNZ75Jl4tRS1TCmb9zQP6W3h2SKD2XTBG4WIWhOv+YxEl+o8juVD4F0+fGJwvWVxuQFUc9gajER0gOqHKBKtN5aDlrK435iS0uWsNNDmJXjSJkZzqV+3p68pPBPTPHj6ZmYhSo13u2zDkCaX5w7MT77c5OulsWeeZp1a7CpmJQ+W75VMG458UDDu08Lef4XSme13uv4kxNKytKSe8EPeE2Vjbrb94OfHz5Qa17gmH2U2zOKcMv4uREmv7pkveLYb82TXpJHsADHG29DwyyZvhsbBac8jJFXobJDr753w0BQGsGQfDxNnHC6K0phOx5KJZ6egUI0K9KZmyhoZ4Xcnf247iH3BbYWvNPCOfzRpK6T1q98o9eFqkpp4cV9bk2OBfJ+hdep6iJz3xCR9WnH9I7FWVydxlHVCo/pR5K5hccqb7003pxbNxI/Nprp704iodPWQBVZCrhm23+YMGo21ke6/gpw8iTT2sIR2CvCAfrcUsRsg9SpeCv8vO26YpYbAFMNC2gmUU6yWwTBVZAm+YX/RjbPe7uKolzYt5j4c/Rywnn999vWumMmYK0/DO6cuLHiBuF1frT1ribZuFuEjdAat03g2WFnQuwMYT28gBZN53rRYlXKpWcRsX0gCfWgLbZhaQpY4xB7cL7QYf95/WfxfviebkJbA4GQvYGkQKy6v+vRSx87mVcLmsWw/Tg==
    username: AgAKGX/GNzKzuoJ4F3bEDCVkrSRRj+PMAJFe68uQ1DyJtscDM5kQQYLtRpP9yVVSuhU5qsrYdq3IQIcN76JcKUn2U6mkGZFsDcHs9HnPyP11p+E1YO81N7LwvxhrozyyOzZqaKBsCychDyMSzgL0Nx0EjazsYw2A+Mp37r3YZJMY0wzOsB2aI6Vgyj9yTYfq9biiPjHWZRXyHLfzCFISdYsGCqvl5Hrsw4U4ezLKi39ZiTD82Jepjh9vZDnTEgBJCJN5JaK+MVCfFnMuK5eFycJMTrvcSsxd0T3XEOxsj7+meRyvAl3t3JVYfAdejwNQJpfiCWsRilV+3Hpmia5uuIz3i1T/IaqDl+h6M/Edccg4KbYkeIGQ97PJrzSbF5T0sPBbCY462ZPGJy5D9IJC4anlDZGzM0AarZaGOYC360V9KbrrsNDtA2/u0BwdOzqG5rOkxltM2gYfLw1Cx3aeUr0VO3KwOjFrHlfp6Fkg6cE+f5B6bzOX21g/kj4I7QzsY6pD7cAWUQgjtlW0rMGhN7pDz1zIwUSNf/3wju0R29h4Y1xL9HXfXWATG3xR2DQpzL93A0CBKDHTpGnhEOUc55upnL9/nTzdmJ8xPmQB4IEXXNpJ4sZt/OhQOiMoAyopKbnOTbfM9a5HktC7xr5JuT2Ac6YGQkxCXoDJm4l/zpMNmSHf3bPBzTj+ZlK2uylxPw6CYlIuNA==
  template:
    metadata:
      name: keycloak-credentials
      namespace: keycloak-production
