---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: keycloak-production
spec:
  encryptedData:
    password: AgC0WFAuvuPkKTXxCv1WSafGSptHYTERd1gOEuUEoJY5SqSZsf2vKCy+l6qSE3jrgMYV+cM2d1lLHkiUHri+gXk/RriSjiejXdBwJlhEKWi/MfHE37evXcnJut0fZi5JncrYiT/912nJG8fIxH5kBDjqu+FDnuuBGiAraYrrBoDVUIwYj/0/CiJSaH1zfqm966hqelhv+Phaqksn1FxAbbfvya+HrxRD2TFEv6U1ulRU4FJRNloFFn1p/SqpxyM1n0XydtvFVXRzLs73SP11zAY4FoofFTL+VSyEDB5FMLEfNy/9eLK780F7MHizXy5MSlp+S1uKfqxjkQMv0GP1zY3hm06TPIHdAj14y5Gs+1o4lj/Vn4E5KAck1D8Qq0kIpDyCHdF32r1Th2iiwN/A7tUuAFB28BBFXG5DB4kPCPnqM+7iT2/RK76DOdU2RuxCL+BnweaQUhtzqP5XEs7fwfEpLUjA5pW3NojyR73dIx9miGfEmtsoMLo5S2S2eWUPIvzM2Al3XDpdYXKPbgUwjtIPG7/9YFA48qZOzTwAgZ7/KFRQEFgEDheTKPpXGRyzWsahB/PIsm1qlIVg5XXEL1S0SDlQ5kTD4CO5vO9VXOKpRK3Wnc6gr7vcZa9P3oPDYUXlMy/QjroztaUfRb/93R4AdvxkgRzTCfQX48W70dda2zsI+prWOBsbOOUkY152mA9g9vrsjnoqoVKP3sobLpVrYiCdzrDzNecCgWVEyNQnFxro/aSIEoLaRTWXIZ7rBnJ6qXzgG8OERsP+GnbC3nhM
    username: AgC2qYeozM+sqEmatH7ogNZr+dbYNYpZJZgwZv5R+EA9ERtVsgowoOKEDAS8iLTyYxi/tIyQuAWPvLPFyf8Zh0MNKGYy9HVFgl20mrC4SfA9F9H4+eIAYqX5hKEIdS6xTs2ofzuorOznCPiV/GvRK7BxLcfJy6ScPJTutmbit4vX8mzkCW94smaVPIGG3ti21FrrFQitGqzWHbQ5ZqrYG6ZpQKPfXAlKlukflIuYo3C/51yzC4EadVJGfJYdOkrj9v1KQWj9Bxdb6sjaLe/Khn5H8lqKR/Mg7LQrhFT8RJWDmXamXXoOdRZiox/oYOZAhgP1EKOIbdhS6F14LhrR+U1cEZ6LIY/yGC9/fmlqSejSZ6EaH68AZ24u6CKFx6LTiPZeSoJ25Oj9/Tj/6vUVqJ+2lstIEQwFd8YxZkXp6GB9Q+MxVJfkv6ZFb+/HNvx9BS6TZU0G/gL24J9fiVFE36Rp8T6xu+43sxOIVPf2dV4ukCFTDkcIb3XE72lYOY24/F3gK1D2PiPT2Hm6aJUmR2k9W7i8zqhiFpgLJWFB3VHbJtZ8uOvv5ecCKdtBg7/PpwVVCUe6k1Sez2PeD47TLxaxAlEAEgxY+Q95FhGDJPfbUcfOA4z5Z8MokSZkF/a/PbbtC/XuuhOW8g+xNkniN4eeIOtx6dxsWlVxGepHtoIpHJvFkkC0kJ3RgRce5C9rmtinpuQ+SuvkOmF2fXg=
  template:
    metadata:
      name: postgresql-credentials
      namespace: keycloak-production
