---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: keycloak-production
spec:
  encryptedData:
    password: AgCDW4AxNtmNFeDMSpKqoS4AQUFHKRYSkuqJorX3Cg7nT4t9k/+YYtDf9jKkLd9PHCiK4lYa+plxa+q2hpnXvbToq4ftBNzw57J9LPnY4ARRtQqQAOQtll3mT/ErwPxJvMLa1nv1/K2qVCdA/ogpQlIt1ELtoZnEcWfmoKcwZftdsfaYOUnbI0W9rAVB+HvwMysierde4TrEWGUWhp4XLeAWrn1tbC33lBF3rA7E1++aPqcpKWVl4Zw1j3iuueqyTcYCO93Z8amQi8Fet1mbKCttVXl/0R6IiXOlk1ujUXlcEtggXogLOMFJhLssPPtPSmv6zsoYXZ12wrUFDlAESkUCuFgl4MG26DKaKIxCTOQMKK82KbrvOpOcao5bqfzl8lRmEeaKfLGLu7YtBqdRxEHfQDmbSpK07vsPUpXveA/KeHoEarstWXagwEoIzW3ng1JK/jOUf/Xcdt/MaTy0jpzhmzjKpq6yp/aftTz8TQfv16Jfe7hmvhsD5S4AOr6WuiDFpIdsTy2FMH+Vs2F34UVZlj/tKk8jQQFFH44K0+SWfMSAfz3zoIUogNikD5qv5sNWeWUZaV2gtqMZeFQ98yybwUGGHFAiiCnZLFv2kQGpsAIvCiumvEW/723X+8npxRi899IafXuJna8oGL8C0a7rdh2veUxsGF3nRGWGAeM3WbnZqUE/nxpOVj8ximh2NqDRnXkzW3dk9k3Gd3cQdr6k3D1ZA4AKywbn4iPPS5TjXkYNPJL4fdifYjHJijjulRVOzTTa/4+F2O1ancB9F37W
    username: AgCt9jg4H6+gXM+4xCJ7JRFypanZuINiCbrPxYsI1jQCzgRnqnfTJwSjUmLm1oKm8A/7tbOQ7VObO3W8jtfWo3Asyh3MY8D5T0u/1hQ2L9UXxNf45E6uB4jN86i0ygAQyU16bLdF1xmmEy77UWDC5fzVI21ZR/GDqWRQRRLqOWrMyXNI4ZZQzUQQyHhlPQEdcQn7dLY91UKO4bP/uPTsyorMlSFlQtkOOODKrAkWppRMHnEUOztNm7C8VzXcvu0Xm+UMx8G+LVsxfurKtjx7EgbzXnpL8w76hwXiY2vWdjaTsFHtXALwati2vIDmIU/8qyrJDEfao8O7JAMiF87lZG9TLOcNj5A3vzaUOC+VdV8oNf07nHGHPYWEzsHZfFN5U6uVIBQPTbdRC8PDRj56MhAWEhjxbZPu9/e1vjQW9L7A9BPTjykCL112342PkfeSounc4BhnGM5OkIwBiID+BdwZJBJ196gkTjFKjTVXE/1x+AyIKksdTDk/qxqEmthf+JINYnFibi5lXbYP1zBXNt4xtOSQ3O5WE97NPU5j3Wg1++i546eon1AZK8+kWooU3EWfqc5WvNW3FnSFCHqmOikFZOcmArrhyr2w4GBmexj3T6dkaqSLKG5wi5zEwt5V7JUdjfRHrtcCaoNnqinCZjtG8jsZQtSpYHYKR8VfMc9Jp5Y6zzEB1P5yj7JnBwsf5I0BeptWcZQJPge82+E=
  template:
    metadata:
      name: postgresql-credentials
      namespace: keycloak-production
