---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: user-credentials-secret
  namespace: elasticsearch-staging
spec:
  encryptedData:
    users: AgBegPK69Asfx5f8ucRBNXVmJgo8SzuUit0PhjslD/uk3U5KQE3Xhri65Nj1ulmtaaKsCp4qoHCxES80vc6XO8dFFMq14uoh4c8Z4t3UGR/BdCCEUdmfGTz7cZvDE9GOkoluoFz12vkpDJL5vopJSqVYlfyckDmXZ4PmyLlZfcCJhjaMq8q+9DgpeBlSiAvYO/3kJS+BiR3M9Ez7gjYP5Wu49uLWgpts2iufytMpsQX/6SlhguimgkmSta8IpkzoPw6otQUSzW6gZm8TT2SmFXi+Da0eC6B0Z9mE8yiwvBnGeujtlUtX3YVQi+LFGYES6F/nAJsQvF4NM5Fg9GO9A1MpxZzh0vaaw8sb614o4HfiLsHGacJ/azLE4/DlDbaM2vu+zyFzGLJzgt7NKETvqTWFmM6VcqbcgQQMfPYQGCkONbDVKIXtqqWDFsCz8Wr6GeKFeBA7b5eY9AQAGMph6Gxcx4jQ2IsUaGMKKNfXZtWL+Gkr7g9fLUue2amlzC42Lo8GcGL9/WmAnpefzLeIEyHt0Upei6T8f6xZmbJkepl3G5taOIod+n2PyMWo2c+WWlwM025QJQ+84ph2j29IpZzBAwB1L7MfZ4UkDDlNyPzRIVrCxY5NPs5Xham6mP43+NP2bM1t+Bs/DPrzTKRuDJ3fXJfOokeyBZI3csWTUWVu2SwcIrcnD5q+qvBHRGJ5m9Y8cfQHJz02NDIL5Tf74OkHEfFMZfGVR/KfmrtOiRMB/EF+9jSfT3+eHSmNvdekdDLEul5M9t8byRFe69DPUfbnKLdldlSpBZap5IMaL/qThATtvZpCFRrUlOWUu4wu4uJNs/MI7pTKcTfopj+7IO3aqCT9JfAVlpR5P7/29qP0hiDsTFA=
    users_roles: AgBvZZR5xYxBP49CPDdTNG/BDm2gVgepigaKr+GDigCeHs+lzGUONBLXI47oEnDgnjevCrbpy6/dPe0ncnonQkYAoAza9CYbmIDh5B6aE4ZLV0DStSjGYBm1p5i0tCOWNTsXW/UO3UbTNSRER4EqYUQR9MxN/Ew2ZW9K9D1arZZZID8obJC3Avznty47KhQfTf+mhJYMJweU6HtFOz9zla/nTthBSdwcvxm769metlJGxzR4tto5CGZ0y8kQDmoUv+UobfIrEx9WHrASEeBBlXZMUuU9OGhsLTU5AdwOCQxQFkurXWVdcfVBUo9HfwP0ma5NKtAUo613UcMjDcHlUYmTL2g2xLcjJervYvDdcTm08RdAyXYIiMTXTzaW+VSQRSPYnAa5h/9/GaF/HetaXBVLQUCQMCoEefWZoQvA9DPcIjmNyHSa6COQVGuPTL6Ce1nGgvDpr/MJdC9Ml/heHcEFmBTpH82YHEHph8DI60zGT/s/zDIrHoOiweyyxPnLNu8dQKBKuil31zY7vN9zPogcJ2afqWjcgkvglhv8JevAStMyYvo/XKCZnJ64B6jrdGNNIqTPwwXsPeABOhROiuRzXQNuBM2kdemcawaBKR1GT9qksbUjYZQxwjcBk3sqby5euuiI2C8nWzvgNua2E5JPnjABNWL0Ll0YaFAOknM2XSN3E9tWz2EcTMA5fcpEOEvz4Bmqx0yZKbvfR47FFCMIwHm0RnBq4MT8UeTVXuY=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: user-credentials-secret
      namespace: elasticsearch-staging
    type: Opaque
