---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: keycloak-staging
spec:
  encryptedData:
    password: AgB/s3KNpwuXDOhfkD0+wQDwKEJN/4fX3bM2BgMBC5vYj4ihoKwmWe+1G2JlFTA0QV+uG+ywT9rm4ehNTX8Snlx/RfIuxQWBNCGlz1L3speHffDayhGRYy51W4oEnCoREbSV7bn/PSmDhPW1b4+pZ8p+fdFl6ST371DTWtJr6xBauF7jN4D3cl4YPKcCYzNfwYf8+uYTl6+NyExmrINONgYSp3V5CzrcIZyggz8+oR/v+D90+e2qEWqEWavb598ns3IydPgSWkkt3tUqE2GZAgR6zeQrqx+CYar3xz/eNefQdEge5RPq8mfpIrGf5UiQLXcFdIUM/WG1170OFwyPmKSqTRCBCNIIu9IReRnBQ7BdCr+oFpbY+VmtgGCmEHofSrvrrFN+RZNi3QZkS5jKlxo6pTT1MDaRR+Gp5veua/t/mWiWoffKHVi9UXP+JHTJEZ4YZwXOocu4sP/J57mugBJH+CsrbYRXNuKt/tzlagB6sYNSB8wt8GHxfQ8Hmn9hUMyi1ZNEHKHemRYmo/nnBipj9trAN4M28uvhcOTk4MZQSipmXJ2jK4m+BWekaDdUxpPdhz6aC+AZpFF6etfMOG7AmrzQvtc1dsFDaR8kgj+6dHMpemCtZyIO/3hTW+oBajn64TZwrqnjUu8EO4ZCyEFh6FZupYNhoRVD2PFN1c/z9ZCDYNheVaccha5wi0vxXBE5fvq8LHz/SHAkJFLCqaycLa9OUxpM+Ki17Okxaz8ma9tjGaTYxKv1Moo0jmxuyvCM65f9gDZyHwb0M9ka+l8p
    username: AgAuJss7D6p2haFcK4Vgxn5or9gLxeWlm1hFKfeMs2rh56johKxG1UZCuRktn9rJs/pcRu4J8Mq/anETSunbwMZ5EsWx3jMMdYEL3nz7oSAwzSJl8mAQ+ztCMJZSHESwNga33MUDq+1ayUs4Q+koGQ90F0E4eH/l0z1y18cC7u9wiDwnUJSaAsdkZfCB7gywt1qQwhKzGu1ocdM1a5zskRsbRcqgPjRG5gahEJ+1zK0HqLHZwsrLxn171fma7QHoFxihoweXADwEz8vdtQaFaOfnbMhK2d6C8eUtuTr9KPBEwpn2DS1EsW0k7BYe0WIcfEnX2WA3mzY1jY+bsWUCfV7opeRi7KOx//zmfw4TsokItUFJYPbDcTJZNAXqFXo9X0gr1iSd/GyUmAYwAv2SWI10ugpx/DoA5mpxcgMjrH77QCRRmKRYTyvucV/PWnfiZgUGtX5zZdm6kgMDuC686EnWfVggUcDneSlQYBWhie3B7bvgtWMx2II0AADZ1Igi5qc8zlEgnMe/ZDFzT81KArs9I3hgZspK4PyQkNGnUN3dSsPPsyceFoxC+Hd9fEj5peiy29Gcx9zu4B1SNtZszacC6oMOTtFcrVX45Qa9d51CPKPQu5FNxY2r5Qr+1DmykVw2FkUpRlGiZt75B9cp1blvkjjHMvfkizmCfeVlvD+Pber+z/sUXPu4d/EgBzkvKu74R6cBSaWcwyNrJdo=
  template:
    metadata:
      name: postgresql-credentials
      namespace: keycloak-staging
