---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-credentials
  namespace: keycloak-staging
spec:
  encryptedData:
    password: AgAc7Wzfl+gZgefosdZiWuAIXMaeqscuKtHU07BFHnOTUW8Lw7w+mVOSip9o8p6n7BKoGtp4Si/NgjRZu6j5U9xJNy16V/ASL1BTegSbZ4b/02breaddbzUFxmGLfYNeFWy+mYhSFuuoEi52qtErtRXGa3VGy2Mk0s6+CJi6qXHalA5MEwP2dmNUp/5qIRNBxE+MRbbwMy00LTwzS/Y3PZNU2D9DOpjo/LnQBeef7VPZ9gtScao2TiAKVvN198q07u47jZ86VgHPfFFJkdz9tFhdOXwVRy+zw4QXNYGVFjYzaLjOESLGwqD7kEuHISsmwVzZlv1tHyA534wf+3ZQhDDnP0nuouovw2EL772sDlwnh7LSbBzfMd4WykCKuSmn0V9gGGcwISDO9IgBpV6kMlC0z0HozP8Q8SdTB7Q2zsXmRTMyXxdfAUPCvKAYG5ZNN6mxtVH0AgPL57WQRKEQxv5lgmDxWi4Df0G373Drnzwa+Q1DHGaBQLZ4o3zVoFyI2hLzIi6azmmvooqTHn8k/SbcGqHBcgnsN4RjrgvzIQA62abx1KW09GqPz8FwNU8t55Ow0opMkrian3r+SAuXaF8e80ujVOuDqY/htXEm6u3qsAfqAUKPombOioiUnpPrhEqF8lWh1zO3R7VOXKkO9NxM/bkWomR0SRa18sdKnXWChYvuZGZsnN9JnEmHTe/83iIaQ2xRFQ==
    username: AgCQx2dxphGs9JJpgUbg51dHCzvSmLuId6nQbzamP8WOtCLMkEom/lScTIlVr+169aUyys02ZAUxEGJriM5+HSTurVJdPXy2cTiKY1UrPoj2T34mdLHKDUnA2VEr0bJPSFBECuVm4fdC4mxt22giYC5T7Xl35OS34qEm6qhdDnVht2mqogjxVfJ2ITUVPQQqrQYVdGZd7ONerZAqd97+euxLPUdWyRfV3gyvM7tCkzOHzTMEtAfjD/RknN58mzRd6zT+sqhPY73ewQrKKIVdT1xlP9tBsFdjSndcEnlcYYb2iCRTK8obxOfN32rIBm+QliACBCpAx2HDtqJv1otCad7MOHeK8zI2cd3B8Pz+PuFPBOKslUBsZrtNcUXjIh+rhXDkg/r91epYkaYDpLEFn3ts1Hiifcko4ZnqlMcxXFfsMXQWYzTj4v4Yl6vSpAFcmWkArWReM1BD4d9C9UInGemE0xWC6cXS1SfQkJuvA8yS0xA4W6eDS/FUnS1HKiobP5HlquNiO3F5QKhLEAx4Ns01u60N92pOe0DIfMGSOOQ9C6WDrix6SZtCyhKw10QQg6qg7e6oLkuYdP13DmC4ftTMwxfaAIwtDUmQqSI1cyK7HhhhDXz7ObaUjOuyMLk1SX8uIjpTwKcooT926clnGnw7HJCHTuzshBxfTBOBw9oAfqPsvqFjSk8AAXMQvpO+ZsUGPzM8Wg==
  template:
    metadata:
      name: keycloak-credentials
      namespace: keycloak-staging
