---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: keycloak-staging
spec:
  encryptedData:
    password: AgBJSmXupJ9o8T0/BjR6COTJfKIoUmKnaYFu9zef5O8PSMGXVX/6aaihhLCdy1TR9lfd7kDlauA8nmGLJ+Jr7xf40zGMe/Pq8pPZhI7GVesCE1Q6Yy/km1L6LtA12NE7+9tLPSe7dZx+0RRuP4rG/VWj8u8KeMvP7BwWFITTkleDsTc7xum7fJY/ATdQjj8UBPpdI/KACFN2K50sn4jjcMsf21lbd1hr3N7pfuIiFvPoTfP7j2aNY9gDIixonlS+u55o+ZHUaaS+37EZlag+jtZA5y5XJ/xZtv1d9WKTYs6xlXXdiXeHsDcwtlK85ScpSc+WL2steKjx0Xf1uVIqVqdqFNDgG+JgKqjfsLvZJ4DyD1PW0I6JUnTBuLWh3lCgRimxm80D0ONel8jJsTbOzLEwcHvZFqttx+87Sr7oF5v5uurQC2JJWReCR6ytBYaWII7PlKhppizQIcyrvZinOR15U7yZWDRXwW1QrR9PxP5qYVeLXx73hqb5RWxLuepZE8xLiEtHww6+cZ3Pt2pzxGZBKWOmMc9rXHOo3Ba1+8kUGw3yICrZL02kGmEjL4e8Fcd1hox2BfOW0WDhukionmMeOMOh2iSY/oKkpF75YLPXsUrJh6P7WkkKowfV7tFuPih1XpfWrWAxEwR6ubNwDA6sAWf57/AyWN0HVGmy+KfvLYw9KozECO7+EJbg7q6NgJlAhC5huFXzZqqBNwDXUBjUtL2h71+HMIw4zUMIlISI+X08ltlqH7lKJYw3K000vKVuizYdOQtKsqTc8hY7kMfv
    username: AgBlR4JhZmbEfn745Sp1d6q80HCTzukeEL7Z50VpTKp4d163vOkQtxljfTX6Pw35Ixqni7/teRSyslJqTkP7aWfI1DosOA4AP9hntlm9gHKwyOAwRa05JmXgnLgholCW5ik74ycBnlUjfGR8rV6IQwZp351ZjGVWpzwR4qkrwddewrm5KgnXXBX+1SwkZWYXgv8yS075q/glX1me4fFFADwJ/rjm6oiFu/DoveLW5pregfKratNuBvkyyWt2SG7UTVGh5K2WZs9tCua7aGzQCmQHAWVmFxAZPabsP1itjI0Hz2/vWc8h5P7MlmKH2IwYVa03iECkeX1cVWF5Lc6gzct2Y0ntgrskKj2YkAVJUN4lZR8TrHJm0hbizDa6vobZGo5lTrHFG46WT8Xh4pfU2GwiluL+g06q34xBtNmyIxhuupmoLSvh6BLwRC8TmYHZNFbZaii6smHfvZnPfd9Wl3yg2EU5xysXwd1Cqp05lxCNldJFS+pyKCSxVr1kzLVwkb1Hyey33mTLQUyQEttEH/6MxP5EU9YwmCPDGEdYDaA9fdNLGmPKzl4s/qUup/kAV5LOz/XimrRYuM2oOrdXPbS5UoPeS1xv7NVPu/HM9JbPA3mdxm2RN1lHQ70SK5aTAM1XhiT5Ppu4JCKVXohg8gvxydEo96X/rTl+CdvsYb9R0lEKaus/IRMJ4fYexb+jbOdnFO7xzMn5psu7h/g=
  template:
    metadata:
      name: postgresql-credentials
      namespace: keycloak-staging
