---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: keycloak-staging
spec:
  encryptedData:
    password: AgCpxweR/vkM/j8hsjDqGEWoGCXmQF6hhsN927dGIsW0RJi/MvYI0y8tT+dd1kRdd5+YYs5Aw+hu/OH1MlWFZolsDq/U/cWy5V8OKhEaRiHhZ55JZcylnF3Ea8GR0emZ8mb4X3MILZrcgZQ1XeL6yBy0RFzqxP764Kq3Ru4+bO7JFIdhUy/dx5lz1bcjh8mImk6Ik0RELPzp7BI6tzJrRLB70hkEcs5fOyQtN/hAqwU2gImXiWiyVp74ZE2jPjFA7BVZbsepzX6JKey5aWaxzePoKuRcsPIlXzHSAuf1G3SFQvs75SC0/7mcV4SiE5OYBlpONmQpHi0oLjlFQgI4jReugyJZx6N8B32i5lU1/AJ4bZk8uXBJV5T5/tKlMnZgqQ3Ik5HobysQk7k9dyFzJA8yO3GrpekcBi15cesons6zbkvZFC9OxsInIoISVenc63CGQHdt1ofLcshDTwcYlXZKkPaDxc8abFvR6u8rILvT773QKCEjOrRLl5opdj18Q5yCicnDKQCaQacGeR6aDTwf6+pgOhmgACKB76l0wpNuE7rHv5Bcaurh/gSIP1HZFUcQj7QVctINZ9GGkqG3MJLE7Kphp9OMF6m6qQrpJj7GCOWgNkY2W7aSxJVF9zgZJTD9wOkiPd7bzGP3fxsmgPkGi4QVNnm02W/PfLkR1SP9ZZusjpfRVtzU642Lou8CcSBeFe20bxtYo+DteQUAi4r73dxaqfuHHgy/1ngqKg9aVxJfPovWQLPCNjajZ7Mg7cjbIghMWob6arA95iSaEbP+
    username: AgBt+z9P4UemSm/r90vp9l401tRzzSHdG5DKnorlsWJJhKJtxPvWJmrtswIfBWMOIkJVWfd8dp9JTk3B9r3poC+bq7H0XSIyLxO2PdmgClJKViqGZLcpYD775yIm/6HcmuezQAZultudUZ11DvE2l7gzd+OF3JtsqHGOpx6/+ZY9G6Us5OS0fsHPmxD9/IHd1PwHXC2jO7h774hc6PGq9fGcSW+nYpIWoViWUza9XFGJzWJpuXV5qEu/lsPfiOQ0J2luccjw8zooMkJuZjMFnxx9TCiYC1GQ93lJt0VbUxVVyAlxj75IH/egexHfTSvhgVoK9ese7fHNlHjRBcUPhxpsYL94fy5KcGBpTtBXICteuq+xesqkKdXY1gTnvxJmGHucsnFeZHGZ+pZjQ9E3Lv3wXtQqA6ij1RQh6gR92sqrnp+aTzF+Zo12d6mUa6b76NyrEAg+pKWwt1E6QaTscU1LkhQoFHU50u8VDeifxUzuIToLgf42UA4TO/43AXJHIWtvpFIcPKVd64kdiz7J3uYMjCPx8IIR0Ebuar+XDfYxBCSA9n/PfRf/Wiv5YX7V3rBELP3auzHOF8u9UOgNHeUKkTcxRTc6SgAfQWV0nosSMzVEq0U1LWPrP3YovGEYs1MXiuPRhYzIFvNJ3xBVP6Z5ARKz7j3JyW3JMnVTKsN3m5c360b3qqfDhaqBIKQCyM5EA7BTQCk03hM9xZI=
  template:
    metadata:
      name: postgresql-credentials
      namespace: keycloak-staging
