kafka:
  replicas: 1
postgresql:
  username: yasadminuser
  namespace: postgres-dev
  sealedSecret:
    enabled: true
debeziumConnect:
  image: debezium/connect:2.7.3.Final
  buildImage: false
  legacyLog4jCompatibility:
    enabled: false
