kafka:
  replicas: 1
postgresql:
  username: yasadminuser
  namespace: postgres-dev
  sealedSecret:
    enabled: true
debeziumConnect:
  image: thanhthong2005/debezium-connect-postgresql:2.7.3.Final
  buildImage: false
