apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry
spec:
  image: {{ .Values.image }}
  mode: deployment
  ports:
    - name: loki
      port: 3500
      protocol: TCP
      targetPort: 3500
    - name: metrics
      port: 8889
      protocol: TCP
      targetPort: 8889
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      loki:
        protocols:
          http:
            endpoint: 0.0.0.0:3500
        use_incoming_timestamp: true
    processors:
      batch:
        send_batch_size: 1024
        timeout: 10s
      attributes:
        actions:
          - action: insert
            key: loki.attribute.labels
            value: namespace,container,pod,level,traceId
          - action: insert
            key: loki.format
            value: raw

    exporters:
      logging:
        verbosity: detailed
      loki:
        endpoint: {{ .Values.lokiEndpoint }}
      otlphttp:
        endpoint: {{ .Values.tempoEndpoint }}
    service:
      telemetry:
        metrics:
          address: 0.0.0.0:8889
      pipelines:
        logs:
          receivers: [loki, otlp]
          processors: [attributes, batch]
          exporters: [loki]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp]
