backend:
  image:
    repository: ghcr.io/23120091/customer
    tag: 0.4.0
  nameOverride: customer
  fullnameOverride: customer
  databaseName: customer
  ingress:
    enabled: true
    host: api.staging.yas.local
    path: /
  extraVolumes:
    - name: customer-application
      configMap:
        name: customer-application-configmap
  extraVolumeMounts:
    - name: customer-application
      mountPath: /opt/yas/customer
  extraApplicationConfigPaths:
    - /opt/yas/customer/customer-application.yaml
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      cpu: 1500m
      memory: 1536Mi
