backend:
  image:
    repository: ghcr.io/23120091/inventory
    tag: 0.4.1
  nameOverride: inventory
  fullnameOverride: inventory
  databaseName: inventory
  ingress:
    enabled: true
    host: api.staging.yas.local
    path: /
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      memory: 1Gi