backend:
  image:
    repository: ghcr.io/23120091/location
    tag: 0.4.0
  nameOverride: location
  fullnameOverride: location
  databaseName: location
  ingress:
    enabled: true
    host: api.staging.yas.local
    path: /
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      cpu: 1500m
      memory: 1536Mi
