backend:
  image:
    repository: ghcr.io/23120091/payment
    tag: 0.9.1
  nameOverride: payment
  fullnameOverride: payment
  databaseName: payment
  ingress:
    enabled: true
    host: api.staging.yas.local
    path: /
  extraVolumes:
    - name: payment-application-config
      configMap:
        name: payment-application-configmap
  extraVolumeMounts:
    - name: payment-application-config
      mountPath: /opt/yas/payment
  extraApplicationConfigPaths:
    - /opt/yas/payment/payment-application.yaml
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      cpu: 1500m
      memory: 1536Mi
