backend:
  image:
    repository: ghcr.io/23120091/rating
    tag: 0.4.1
  nameOverride: rating
  fullnameOverride: rating
  databaseName: rating
  ingress:
    enabled: true
    host: api.staging.yas.local
    path: /
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      cpu: 1500m
      memory: 1536Mi
