ui:
  nodeSelector:
    env: staging
  image:
    repository: ghcr.io/23120091/storefront-ui
    tag: 0.4.4
  nameOverride: storefront-ui
  fullnameOverride: storefront-ui
  extraEnvs:
    - name: API_BASE_PATH
      value: http://storefront-staging.tthong.dev/api
  ingress:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 450m
      memory: 768Mi
