nameOverride: swagger-ui
fullnameOverride: swagger-ui

nodeSelector:
  env: staging

baseUrl: /
urls: "[{ url: 'https://backoffice-staging.tthong.dev/api/product/v3/api-docs', name: 'Product' }, { url: 'https://backoffice-staging.tthong.dev/api/media/v3/api-docs', name: 'Media' }, { url: 'https://backoffice-staging.tthong.dev/api/customer/v3/api-docs', name: 'Customer' }, { url: 'https://backoffice-staging.tthong.dev/api/cart/v3/api-docs', name: 'Cart' }, { url: 'https://backoffice-staging.tthong.dev/api/rating/v3/api-docs', name: 'Rating' }, { url: 'https://backoffice-staging.tthong.dev/api/order/v3/api-docs', name: 'Order' }, { url: 'https://backoffice-staging.tthong.dev/api/payment/v3/api-docs', name: 'Payment' }, { url: 'https://backoffice-staging.tthong.dev/api/location/v3/api-docs', name: 'Location' }, { url: 'https://backoffice-staging.tthong.dev/api/inventory/v3/api-docs', name: 'Inventory' }, { url: 'https://backoffice-staging.tthong.dev/api/tax/v3/api-docs', name: 'Tax' }, { url: 'https://backoffice-staging.tthong.dev/api/promotion/v3/api-docs', name: 'Promotion' }, { url: 'https://backoffice-staging.tthong.dev/api/search/v3/api-docs', name: 'Search' }]"

ingress:
  enabled: true
  className: traefik
  host: swagger-staging.tthong.dev
  hosts:
    - host: swagger-staging.tthong.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
