nameOverride: swagger-ui
fullnameOverride: swagger-ui

nodeSelector:
  env: staging

baseUrl: /
urls: "[{ url: 'https://backoffice-staging.tthong.dev/api/product/v3/api-docs', name: 'Product' }, { url: 'https://backoffice-staging.tthong.dev/api/media/v3/api-docs', name: 'Media' }, { url: 'https://backoffice-staging.tthong.dev/api/customer/v3/api-docs', name: 'Customer' }, { url: 'https://backoffice-staging.tthong.dev/api/cart/v3/api-docs', name: 'Cart' }, { url: 'https://backoffice-staging.tthong.dev/api/rating/v3/api-docs', name: 'Rating' }, { url: 'https://backoffice-staging.tthong.dev/api/order/v3/api-docs', name: 'Order' }, { url: 'https://backoffice-staging.tthong.dev/api/payment/v3/api-docs', name: 'Payment' }, { url: 'https://backoffice-staging.tthong.dev/api/location/v3/api-docs', name: 'Location' }, { url: 'https://backoffice-staging.tthong.dev/api/inventory/v3/api-docs', name: 'Inventory' }, { url: 'https://backoffice-staging.tthong.dev/api/tax/v3/api-docs', name: 'Tax' }, { url: 'https://backoffice-staging.tthong.dev/api/promotion/v3/api-docs', name: 'Promotion' }, { url: 'https://backoffice-staging.tthong.dev/api/search/v3/api-docs', name: 'Search' }]"

ingress:
  enabled: true
  className: traefik
  host: swagger-staging.tthong.dev
  hosts:
    - host: swagger-staging.tthong.dev
      paths:
        - path: /
          pathType: Prefix
  extraPaths:
    - path: /product
      pathType: Prefix
      service:
        name: product
        port: 80
    - path: /media
      pathType: Prefix
      service:
        name: media
        port: 80
    - path: /customer
      pathType: Prefix
      service:
        name: customer
        port: 80
    - path: /cart
      pathType: Prefix
      service:
        name: cart
        port: 80
    - path: /rating
      pathType: Prefix
      service:
        name: rating
        port: 80
    - path: /order
      pathType: Prefix
      service:
        name: order
        port: 80
    - path: /payment
      pathType: Prefix
      service:
        name: payment
        port: 80
    - path: /location
      pathType: Prefix
      service:
        name: location
        port: 80
    - path: /inventory
      pathType: Prefix
      service:
        name: inventory
        port: 80
    - path: /tax
      pathType: Prefix
      service:
        name: tax
        port: 80
    - path: /promotion
      pathType: Prefix
      service:
        name: promotion
        port: 80
    - path: /search
      pathType: Prefix
      service:
        name: search
        port: 80
