nameOverride: swagger-ui
fullnameOverride: swagger-ui

nodeSelector:
  env: staging

baseUrl: /swagger-ui
urls: "[{ url: 'http://api.staging.yas.local/product/v3/api-docs', name: 'Product' }, { url: 'http://api.staging.yas.local/media/v3/api-docs', name: 'Media' }, { url: 'http://api.staging.yas.local/customer/v3/api-docs', name: 'Customer' }, { url: 'http://api.staging.yas.local/cart/v3/api-docs', name: 'Cart' }, { url: 'http://api.staging.yas.local/rating/v3/api-docs', name: 'Rating' }, { url: 'http://api.staging.yas.local/order/v3/api-docs', name: 'Order' }, { url: 'http://api.staging.yas.local/payment/v3/api-docs', name: 'Payment' }, { url: 'http://api.staging.yas.local/location/v3/api-docs', name: 'Location' }, { url: 'http://api.staging.yas.local/inventory/v3/api-docs', name: 'Inventory' }, { url: 'http://api.staging.yas.local/tax/v3/api-docs', name: 'Tax' }, { url: 'http://api.staging.yas.local/promotion/v3/api-docs', name: 'Promotion' }, { url: 'http://api.staging.yas.local/search/v3/api-docs', name: 'Search' }]"

ingress:
  enabled: true
  className: traefik
  host: swagger-staging.tthong.dev
  hosts:
    - host: swagger-staging.tthong.dev
      paths:
        - path: /swagger-ui
          pathType: ImplementationSpecific
