image: otel/opentelemetry-collector-contrib:0.104.0
lokiEndpoint: http://loki-dev-gateway.observability-dev.svc.cluster.local/loki/api/v1/push
tempoEndpoint: http://tempo-dev.observability-dev.svc.cluster.local:4318
