---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql.credentials
  namespace: kafka-staging
spec:
  encryptedData:
    password: AgAidouAdiSkRrhGTNCmOr5xAE45zMuyIHQvtOz23VJvnuo53igV9moAV5+fRqoxBg2Q0bwwIBcIGEEwn5NiTd4wzT7MIa5wvvgqyeO6mNVZMLgX80L2vd8V4+QA7Ey2/hyp9Y4n/gGPOiT5p/VI5ccPcGL8hQWiNe5zxzG7lO/hK7wLQOFn5fAv3SojmYyZJsM8Yfv322XYCHtCiJOQtTT/QD7wgir9pKVe7b8weSwiIx18CYAsRFAt1j9U6ylaFppInmu6U8CB73GPPbCNQjNgHD80w1L6bxpKacv9ts0qXdvFNFl5wZE2IsbEYETeqhQuGaPNWZhCMNso8RzjEDWQ0iVtvLNS1yQb7SOSnpgHkCMLI5jgRqpix815UH2lHM9YGQCMXloiCIAIfQpriAqFGO75GMDosFAFzkATNalKk0CAUZ8WGtw/F3hdHgPR4XhaSQEVdEPxsqt4fO58SOT47Quj7bGtgnRZp/XMXZBm6t/LWEshS0Pa65MIs2qG6SD28F/rYIhb15dui2HEu6SpBZCdsisRZWEY0ChQOdcMve//ds25wzvXOHxN354fVdjEvU98R9ZNIvzssYWb9ENur2sG1IBY93xBca7hfAuiBSaJOEy94UY7/7l1FbOeEe0F9iQOCAEClYqHHJQ7ijB3WtUyRzmDCqrVDWD6v7r52j0Ke4ZK+m0K7euyvxGZrPh2XCoWrv5HLUuRCJNWYngpgwMm6++jg/rvqOjsoHNonwjadgVFEvG4ZKl8zumsCyxU6q6iaagU67rZBJOGfzSe
    username: AgBzvI7qsv5U4pf6ZChEm/UDFfXf3w4emHd963ueB2e5I1idU4RZQpl4yYgIS9TV9+W52Q6TEU9uvzitJk2Eq3u+JvedOMlxrdDHcYGFkQjGQVkt94KtrW1yLxTu8URbDxLMVOR55kXvSc75Bzz8XUqf2yBpWX939saqRZoH6y/VfPSkEozwfYUzcSt8Kz55oSza3WN3Q6tBrOxWtvmN2l5K0reHVBwhFnRz1oT7drsPovCmuUhQ3uL4cnf2ejn9Nkl1GfM2/+r/idXyM39elH6HxP+YnNe12CiknjlGcD1fTK3BlZrJqBuV3/ztnnIzgQKNwp+/MY+E8rBiibeuB9JLrndaD3Y12RuU4AOadybEJLQoTXG0nsU+NkPYDeaOTWruqfFyoOcT5mS/R0MNwJUkKDopT7cOqSRCFtyxDKXHzQcWBEwxDspzIckgDbAeMHm2OPWmsZo840cCldZKEqh9ij6cRly4JU5E4FeNYEvoIRfX5O8uSAqnoM7akZ6MR7iElgPvnhonRZGscefSK6l8bgW8Rqcx3piFvOGcyuWjZwGmGQ4zFSFOmUmiShdVpUR0Zz2s7yA+Hy8N4jGypc+bel97Gru8gdKA1Urg+XRd9N+Jns/2liJGO3MTORIxNFk61bxkKQsFiUBD65uB9CNOCGwVA8w8Hqz9kjgVhIeOqy5kCVvcMOs4v6G0N2M2Ugh0gkPio7XLMEzCecg=
  template:
    metadata:
      name: postgresql.credentials
      namespace: kafka-staging
