---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql.credentials
  namespace: kafka-staging
spec:
  encryptedData:
    password: AgBg3DU6nYiBwv1VGSVOEiOt5g2EAm8tmVyNWilb7skOh2f62jKjCZUTZqWtEthBMaKtS+58ru/eOGkb/49HyFIksyQYJniEUTyR8miGDDQqW4+LFPqG6beZMBH3MO+CEsMN+knn/H010sp+RNFWEj6n+QPXmKVKJJErrQvUiHz6Fa3uVy+WXccNCtmJ0uXO5GBszSn+UUrHwe/1ovT1y0FRhh8m2g1c+5PAGiALHRcflA0uVioxwNmhTXkMw1UX/SwlePZ6IoYFDAJdGr9t9oRzktCqysSBgcnG1mjcghN/OdQGTYnGpB0B15QdUOxl2gVxcFCaN3aKe5AMkQvSNq1KMAqMFs8Ji4uAB4skJo+G7cxa7ud+tp8FW5ahJGbefEnkKQQ8/7EEfARdccJxtUJmJQ07y9A4hPiuetrEIOxJB8D6ptV9o/fge0wsiPdy48YUlS5MKWQ7X6BHhmk88++SKE6VXW5Koji3JZfkJqK/YT0oRHGN9CEuCkK/QbODhikna2YRwpr+Ic6bcxLVekJaEJr4uKFJY0d6dj77NN47GYdk2wIrR+3SM8opvZGRX2s8Mr5Vj+nOkpWp1zSZu4aubwHakKigjBeiEjuouFk1HeX8Ag4dVImC13QSJbtuZOVPttKudQOEgtsXBEiny56raQFi99scv2+hx3kfl6Bu6r2CA0ZSG59d+KClWlwInPv3fIOuKdc3t757/JCBJgOgy2rX/CSafMBOBmQbivS1ogsynWRljoMNlhZn7vYNuHJqgvneFGMgnXtc8qudi7LG
    username: AgA/nosSNoXeQq08H2MLRVCuZqB2v2be8cg6BDgT4fHlHLbVH1vqJTucbmBiumSA05QaXH6jXq6KUX6glQx6JfYzIE7YLqQHLusrdiDwt8lZrnibs/h1W4+NYH9onCcYv8Hk/06FByRmVJNtiiEFuXgBR4xX1dn/2lpz/T21LzrTILKjr1j98+7EyFRsf1g4mgqp2Jf7B9kfNpI0q+w8wx+Nsq+IBDKR8jq63UqBiacwwSlIOdD9vIix7VG+LVU1n71tswSjoVadP4QeHE1xHvgdgwX4cYpSsGINRiP9Fj/SfccBfl8I/Mg+cR91UY9yK6FIAvVJDU1Dp6WpTf65GZpb7KoA5u4qs/5ZiiqBYAaelotHAdZHkK3MFWGkheXpiSqbkBHS5MKCSWfUeI+Sbs971xAhfHI4gqGKWH+/NGdeAjZuTOV9M/CWC/W8PiCSCFHf4JG8gDJ+/KYSMbqHmQTip8R1DU6YJ2PkRwwYOkokPhNt3noJGS9u6PGU9WTsdAMBnoNeQX65aoq9To90Gr3ZIeoEis63YMrfxJmQGKyEJLQf8pLvBJPuQ+dfDZ3kF73K8z6WDLCXBCHNW3JuyP/XkABZ0fXYaEc4fbV2TDXgHknsu4aUsRRBJuJW5XYJfmJ1xEAy3r7Emf7IfV7HyUYn1OS4HD738aviCkMHEJj2FF1mSqfi3/10O54Rz38HTlH1MDuPaESBy369a48=
  template:
    metadata:
      name: postgresql.credentials
      namespace: kafka-staging
