---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql.credentials
  namespace: kafka-staging
spec:
  encryptedData:
    password: AgAlVM/cK5kvD5PWW7dy6HE8G57kF3rf892zFafC/geLjXmBnGfh7hb/gALz/jhts8PlY9NkVQWRAUqFY2B+Qn5ifWITM0e/4p+4P7wqaEO8a2ARrhckZDgcDSPxSAkzOJqZ83z0udd+RqOSppuxSExgvxdqcpX6xPji0wrHrr9xglQFvfX3ubs2HN9uzxtD69vBXc5nnfYsUyzDUAsN0G29Lpkqrm/UqeUxEvS8dmksdtK5SV9BpPVjz+MmJkYowEZwWv3Ydb2qeTvJ/O3qbX80jNgWycei2hJvx75NCK7Uqv2Ar5czezPx35m2ovrymejzCE1ED/M2bqVf7wu9zCtni8yvKs7eRfqqcG4y6+QvX+wqSHNPg5QZZaIo9uCH+Z2BK05xoT+9vRUh/JVDEu4jKIcpNrBhm78/JOSIjL2AvjFco/Tt/k8TbGS2TLOvlozDopoz70wXVbag8T6IlkGXYlQhdg+rzcHgxf5KYJ+faf6c8+0u7sR96ndLELR9Feb1fbcYfIk+doZn0oA2RkDA14DbNOsDqrfQGT3U+x7jzEqTCd9ij/5/eYSPpvDQzH4HNXzxdsABPbJvfBN9yLCwAYmxiSQU7h5DkiX1Xd1Mi7/RUB1BgFJfGTME8eTEhidCb1OJ4RqdN6mJhbfAwiXdm7AUnFT3Yni1fSfH3c/bBtpkRP/jwk+cfwtFetpf1uFe171W0g==
    username: AgAI4uNOOMu6h/RaYJNNp/rOGMGv5G8ykzw1my1ZDJheCfvEBJ67cPpoHBPX9tSKjswmftVDXz0tJDOoOtkNTQ0RS7CIKzcIs43AdQaUKCS6NltzF/BSyogJW5Vzp7G3qkdb+Dg/GNmFRSDQkeafsyrJCaFFsGm1rnEbbtW34IzDMNuj56a9QuMQSLDJ/QI3DmhOMn/KDWmV/p2UrbuWmxwYPmdRKXO3JGkgq3KYXZEDQ5x2Z7ENJ2BNgoL998XNBMLI/raQvimtOSRrTylSR/I//dZOEHuH6IaNqwsFMMXibA6G7fpoPLXGqg5ty/Kpc04G+zJIuxL6iMyEWKIWlsODQGYgHKDqQgAbizWiWHiIDTva/5+pyDwsTpT4fgfNtpfZYGgIGhnS9n8AE1RUNAXRkJnOYNmgXlQaSj+nZEZC710qM/gzvxjmZ0T5DcjYXE6vq1dcQzsOl6fTRnl7gDUoVuGBu4vYQpd5RlAsAX2dIw4G7AlGtM/MKbBD7jG55BnDwLDQmeuXXIi/Z9YzuQBZgU8ty9WE20s0giMbRUJDk5G2qcUnWt589fywPzoDrI3c1WzPhoJHdC10MUAaGpL9NlsRjEBFGLRpHWM8iv1c8mKbt6PCRBTcbqabNoED9tgDoS5XCpCVFnzyWN9MOukTN32uP6ERojiqavDWQAXbWejVk9OElsCq0ads6vJ6JVRybTaf2D84ytz1f9k=
  template:
    metadata:
      name: postgresql.credentials
      namespace: kafka-staging
