apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 9.2.3
  auth:
    fileRealm:
      - secretName: user-credentials-secret
  nodeSets:
    - name: node
      count: {{ .Values.elasticsearch.replicas }}
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          {{- if .Values.affinity }}
          affinity:
            {{- toYaml .Values.affinity | nindent 12 }}
          {{- end }}
          {{- if .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml .Values.nodeSelector | nindent 12 }}
          {{- end }}
          containers:
            - name: elasticsearch
              resources:
                requests:
                  cpu: 200m
                  memory: 512Mi
                limits:
                  cpu: 1000m
                  memory: 1Gi
