---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: user-credentials-secret
  namespace: elasticsearch-dev
spec:
  encryptedData:
    users: AgAzypO/EMJZN1zXAyRvNQKmPHxCr+lCYOVzZF0p9VtLW3V3QHDNJ95fqKEDLrTbrdW/El58AqlwdiiUCCU5By8E295V7HA3dEFhdAUeKUHMjbW7oQmBrDtmqwTIBFYdhhrZhAXBh4GTPJ5wUZJzLiD++sTXHY0UQQ28/6vd8hnY/WoXN/IjYAjR+NuPXzlpApQvD/Spbx/mBtzjBs7Esaf4mn0GSW7J3t8s6CO5VIR3HNML0izEkT9gIIox2cR1EfmPhfzPpAcHWl8EiodQGjZ8/vrfSYTQyFM17e4Jcj/cP1wPbr1uPgAy71bisGTqglAc4VVgKEm1iyXoVUvxyrzhQ5llTsbVXRZ5lw7M+niKjPiFsX4b3qCX7tUdYCGNwTganMsOWG3EZPFGFSiBBUubLe5vfsJALV+7lbPOvBUsR1si/4VqEKTGIeE3uvz1f6MpW08xzWsI79pVqt6jUlxu/Om8QjO+v2DRnXT08H6f0cQckPVMXqap42dQzJOoguTXCz0g2CrzRLTbJckLzlCodOIxZ5wL7zKDmyGieIyDk/9LjqYLA6pcy84XlCHe8qph9QuBf2AsVs6Kj8zvYXtn1UdZvh4BaTYLkBtJazkRJFpAb2bNd/aOLGBvL0l3f32Hy2C8YssrymVpLL5B+yVWA9BbsdBY3LxhsGtv2V1Y1m0u7lMozHGSXhsY0wFXtJerahiTru0jiXoVfbtktKFtO7izArI4JqOqbQcolyUISQwHj4c4Oni1X9gGAH871CShc7KTs6LRi3n0HkMpPcbrIdD9ewwEEzLshzwNTiNcE7XNZTfldEkVEbTY4y9sM0IKvHKadszCFYvQTu1oRSPthUXBNvmC/mOnicRzve1P3RGqlPru
    users_roles: AgCGkvBCot8JoTWicC4pqgsDe7Vbob0jWiGI+Aqkl2baDFJGaLGWHaxwsOi4K41SWtQ6deyFSevBbaU4k3dGM3n5N7d0cuxO0WHP/5FKNMOrzLcI3txzhIEXZE8MiuMb5ZbMUeVgbEVDfDcJcAw4y/6dStJ05lo7AwOc0r2YSFkHcmSmioJtVKXmpa448c+yiIy66+X4maAIRMzt5hDckpX+XMDNCtG3eQbdou4iGLeSAOpCvXI3JPw/v1ZonWoHNv0+a0duQU0UgbTU7t1FsoBx4EqTxHQeWBJaBsq1ePVJ4t2XtEhIFdZ/xMrR1BenhYftK5y0oMSR87LkLIjVdz4YfFMOt5EYyg/CVQp76AKTUfRGWvUfu0naePQsS0168JH1Rm8oFH22wEjq+JVVTOn8PyDHRgRr4cho5BabTZksVXyDumaomJEzZWIbloHW3ZoURnRaD7qDAyGXKjLJiHJ2fA3XjWnf+Mp9HqktYACYGMUUunr0dCQ1zPsEDP5qSDJucZfjllatXe93QZNfqdNCXND+5MxGFShlqPCQMGToSfQOTxZWuQFZerYaKVs+URAq/AbnJJjBUO2WOiGJ8C/JZuBzDMRmvE3d5Q329HsbNgkMNQmA+LeZeIOxxx4iOeFOgDyJsS9Gx806BRj+QJDGwPlRy5TZMsyjkMp+LCspUJBakop2IiaxjbYittn7N5+W5BEm2GqwMWhpsQL2k2AvKf87u6wujDPt8IFiepw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: user-credentials-secret
      namespace: elasticsearch-dev
    type: Opaque
