---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: keycloak-dev
spec:
  encryptedData:
    password: AgCe9qu8UX5AQfyj8AG+imiz1XL0cBw4ZoPIK2189EJuCRyn8kN4FTywd4wxPgNJMRAyvjEQ3qjUxlqR32C9ttBnn/7MtfgrJ5F+u7FE5LUxVKhg2ZhOIRSmCAJFt0BiLaZEbeQYdE0AGt8Xz4uDHKE3FqfCnDfVgu0csIlD08IbI3+ahhkZ70e3LscloqLXl1qeed82PylwOC6aM2JWOi3QofrmS83ks/joFE7w+CynNsMA1GP1LvXj2mZOY/437tk6yMA/+RFccVzQUqSMWirOOtDTBMDqerVV38tUg2QR7BcsHS4pINZVICCyQm9O/4jSOMcUsSdDzXWFPzFPa7XP8c5pF4aB9pW5qqvnmhRtrBAXOufkJR9S2rgVaNbpg6sFVpPLUxkGb9JOX21YTfaBTr02LYtnV0Zd/cWgeArsvntnrn+IGYlvQD3ogFfqQh90fAHpuoooO6ELOfOw5nNR6GyJjyd14+TmfCPOD/sNGe0WCf4L19Unb5QGR+RaO4VVAw3kU4I/09G469vcVKbahYZ8sL05bV2vpPvZZruAVhyKsLQ/oo/57PL2t+mJlm8xSKhTFkNoOhtRmj1I+6cXVJJl1lli9PgO/ReY+pGhzNN8GrseJYjROC+sWP7QVKlagskPjm9obYSyRM0vhwVzUx4tqtKHuR89p1XlawyoYF+TpIgr8VpNI0WjFfK9MzYO7fkus0aJSqL83Nkyo/WUGNh8bqR5i96EPAQTBgtUFEQHtZWniIF7ts0CX38tUAJ2vh478TSNPGhangrijfDa
    username: AgA9cU18Dvp8l+S88+CyIrb/b9KAWFwd78FtRDggBZEUWqNsW9uzMp83G2YFo78YgbV8CW4xclumeWnwqN3K6jbu16rqSg6Uz4gRj6HmNxZrttvYOgvpBin0du5YpMX50OVQTmDIR7CaaE+1GA1jBt+jyVIM4/vijj5eCqK22KnMtpPFUUAABg2C3qUQ0GPH/33z5awwLwIFywWDJQlnPAda7dHzUTVY1q3sZeQHtljnPvvmYJmAYJ9Mh8Y5NPbPKzbTdT0Jug3agS/zBMFcBPgeAKU/87lhy3OvXm+BPILFSHexLHph0WOazTq9/6b24vggLLjoj8iOddjm6Nij7skOcw5kOW0zAyU3f4p2dZZ84/XQ/2Y+JvPg8NChTUbGm6Cp8ZR0FduTJa+6yjADIt66Jq5nhvbfTIbVFAln2IUgOHVFh/6lSOKn/XT+lhAw/Y+rABrzpqM03xpcCbQhqlTKk9L6YWuNW/24OoKEQFH8xPxZnUV4KPGGRt/dFdKpnWeZIUelqqFSWC01oOzB3uTHWHfQ4g+zbgWie4Kg7C7dxzj/bOUyFWc8bhyofbIDiFF0qeN+49EvU6sMQTS4CTxNmpxzQ1PE4c+j2D21YWeO3Fta4XoXXTFmf4aWwvwfRQHqtgnJ0seLpcznZysRB3aK4Z2uK2DfN4ao/5ruzYyH2Yphbb0eJnW8kzbDlYAnIEfKQ7zeysyYIRUjyqs=
  template:
    metadata:
      name: postgresql-credentials
      namespace: keycloak-dev
