---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: keycloak-dev
spec:
  encryptedData:
    password: AgAYCH6CZGGcyJWtrytbUxB7nx/gD+QImnFhCoH2JWZJB9GwOz8c5bgU5c33y1yLh97JW0/DqmELLDTdi9TmYFDwhZmt3Sr1OzPcPwqR/QAywpmVvxuTYUqz/HOmJhb50vg9iREtA5GTaPO0aqJmT3GRJKJImpC2ZrL+iYRFSuk8K4doaGIK9faY41Q1K2kgsr1QhcA1p1SyTLZ99vzmkAKhF6l9juUuVcLbCMAl+b97mOrYvG0pXkpXSZG3DzbMYbu2OKWhsVdSTBLcloMSJc1LcHSUNhsJjzsmSqRlU9hIqX+G7kZ0QWr5S9MTJjzByRMDXxFj+dnttNT18pzIndOEbSNWsav3uspYE38R95Dbtu1ZdhyK8sQM8+wQvR1vRcl8tdkq5zZEaREBD1ypLmmSNd1LIFRZZE7Sy3qiRZUdD5vngbF87nyNEnLWfWD3AgM7hD18XoVZ6yBD9MysqNpBt534VbMuih2Z2lisiZGeBHUiD/JIMO13TV6NUgBHLTEC2Or/14Kri4W9fWFWjjPNeeugcEY/VDAxNNnQuMfXeaPP+W/72B8+1mp22KVtNj760RzHql9mkja+k3zBQoKXcs76UieGLmAY6N59YDhl+JP0GIeH88uLPNigeRiI9QJyc5QPTVQ+2KizcC6ee2F2LjamtzaD0fZawwVgChQSC3+LLPV+Ucqqwd1UjJ4JGTpcaFB4vpjtqdjzgIvdZmU1aUwAV4d92THu/nj4aBwjCQPsGe9FMBol4B9LsgP+4UZGSe3SkQpJsMaXZN72aFlU
    username: AgBmUufEphYF7A+5oqjJd9Pt4bcGl790Ansof03tS7RdIBqCPbG2TPGo0tZLBpFXVWRndjpque/yuhJHeyx+h/y8cySMIRWDFQrILaPv92JM4mrNxr2izFMHf7BtwGAM/7/0iBVLHQpHs+eohwcdIAMv22dAvKd7lbuXYkxVlYiPF58TbX++nJuItPm36Eq88W16Xc1N+c99AD92ZHWBPWQ36kpTAk7/p70F8E2jLr8KS+r1s7c84ZdEUj5ssTshFrgK189U/O5lBtXRGW3Q+VgqVWeqCHPR+P+ZcGUsLnuERDEcpFrbhg5d3QzqVoFkBiGk30sEJoIVgtGduSgdvieDvgkJqxUNDL6SOr+6E6TzYrB+EIO3diVgVVe1NhH3K29O598G2yU45Bs16bHYOtEkrupT+xIDB1/QlUGDDN0deUIK0FDsdA2Ve7PtR/FZriIYvpTr1tL3BaDwliEBIKX1esZSNZMgwSlnzwGyS5w3RNc7ARhn9mdsFYX/C05AlT+eM8g//SxPlcYtN4fmCSTfye6P2LxeTeSEf1+vyEdRo7BS6dkdSPlGkY3l4yXo/gH5O0wuMiS3lX4inOHAm+Qf6WXkvliukYVDca7S6M/EZqnbsXKoePc2jiLNOq6QSAypj8Px9zHY6+4mpK4aBMUf6JRUJzzvWcEje/GFHiSCeeIRkXuvG/db9vQ0b0F99nzNtItc0Sa8E0ueK0I=
  template:
    metadata:
      name: postgresql-credentials
      namespace: keycloak-dev
