---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-credentials
  namespace: keycloak-dev
spec:
  encryptedData:
    password: AgBdQ6DSs59H3FL1iKOTXhGk7vxpLCQdI0AAHPfY+Fb1utXlDo7gHKHL074PEBddsddah8upfrLiNhOqkC7dn6PCQAB/SA+XT8KzW8+WryWtzPoWHL95NVc6mQ+20ix+xl2ZDhHzokyAUQyxMmuJan7RrS38Zmyk7nFqDShsEuEq7VYgoxTUe7i/t4Q9yT+sWllxCK8SnK8oWE3A3CJDpgTQ0/gHwTiIMZTqDCt7ecvkDKI/pdS7Qdq2+O5cUZpvRpoOBEaKmVRhckoZs6NhA9aRFmw1FLydKalmUFVlLlisN1eyLeotM4HQdTgZi7Wk9Fm+AwTdc9Nuf76CuLPaEJ/I0jTkMidlTdWyom/yz9sWq9oUiXFsLVPCoNaGcULQUbIez5OtOlwykLSBgvSD8fZ5RnW98z6H9V1jVtM4RcEkksyupC85zESWzekWKxAiWUFuFO0BgTugmceQHYySlfhvSPG32Vv0y7MPu/ceMdKkZFwemQt8xKkbLqxe//BpbIWPw05aSF6QxUfMdKDzDMxK2hii/PGh/ZBaQKMebyze3lRQcxFzLrsUJlkiq/hxuJ9PJZLeMFJbl0cbLjHdjVKp4WzeYdZJdGtb/lAKoyfKOhXKhTQHgTnM3YTx2n+2xI8UYJ+vE2Sjrj+r5iuKdqVbWJMchagl136aRka4nReqtqQ33QGI6A4ah2AZWsbV2hK9n145KbtqZ8yI0bvDPQVtVtqL/2Tr/8Goj7CPKUO+1JU6azOUraHr3wa3gnJorLbkLLLBlW3fvefCW1+iq0+i
    username: AgBFztJopGGaN220jupNtJo9aHXxEjdO9ae6HNphRgnifwEFsex/XV0bLjITfPFu6AyAclS8NPJgUQlDPmTku6kOFivVK52eGORe7nN15aWQpHw6PoFypCzaiLEflpLBKMvKUCU34V77U4L+t8WN03L9QEgoqwIPL0cEqmsWuCFoEYxiGe0A8z81CF2O1pORf3ghXBm2OdxbNRbS0gkbIdaKdbrXfBwe87DO1gqFfB8g2E03mlzEqC+JiZbuxJYyi4rmQyGDNlGtamJOoZgC5wQVrWIrT4jrJjRIYt9llAoTnMjJVy05SsEul+nJuLDYGMDYRApEKzkFJOBV2Dh51mHMHyMFhgcXSG3y7bSwsloCIRdCB7GFOLAUCRG9rPvDwxl793CnunjjzDR7fqJbhmt6G7vDwjXpf8PfOVJZ8bMpRBhi2lk57j9T4eVnwnEyTPfNDENptfS4xixFRGglBW53hwrPhj0/dXIb7SlPdC4B4uIJyAOBJ6B/3IcNZ35AZVnuDLdd8owA2WEw1qOzQYkap+kXS+UVYNJ5Ys5Y1NWH6WNzQVpyvochJC2VxaetzNuX6osK9cXml1kIpQ4KVcueVztPHt0q0xkVb60iTz++KZBINhP2ZJs6P/25HZaFOWGaVqMNW47DornIs3QugjkuVH9k/aRCWXR1+l4PfFDJP76vom9Brh79alpernPSegJ+41NUwu/7jEN1950=
  template:
    metadata:
      name: postgresql-credentials
      namespace: keycloak-dev
