---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-credentials
  namespace: keycloak-dev
spec:
  encryptedData:
    password: AgBhCn/th9RP+AgP/L/nWoByZV7rWt04V/kkzaGlmlhCqdbqcnIuqmd1G8mOqMId3uBOFS2Ob6KuCbOFfGrgdvPCFdmVd7NahE6cBUNaf7YxzeSxCn3ADasRtX0QFktTiosRr6EncawonJuhv39SoGEtm1hOEXnars9V0S0q2PFfnA7z3xe3Tq9hFTdbgAZ272pRbmKCICBLmCpg72p6GEHXz16U/nVDNSO845dacB/AgyffeWMGtuInIMKfiZOOh1kqbWQRpPO69l0cpFILt5NwXSf+j6ikyv7zTNjHxEbYEXNtedqOdmzQfK+gK9RLMee++JZLfuCZK26xer87y65wl7aKBmXfhFEp1DWLnFgtBY55hrbsHwAJl1zB+SmT5h5ovYx6bW1vpI9wsF41OBJaMAmSpGS9yVSvpEhHnhv8i4JcqtBnPpvXLwLGEk2ZWwHNcRe666vGOD7Qf2kMRJABrQ088jqpI3kh7GsSKarR9at2mOvWG4vE+0xHIjgnsh4QI6F+anDBnnrtRrTPO+oIe/QJhxeYJaHnjZCiZR8n2JpWLmL5/HbWJOPQKelaL4l/O/6mFxwSRXhiqFnmOge5fa1yXahYzfhuCeTS4AqaCLP15LjfpYz70YMjLLosDxH8sqfFb/1qhIz3nGK03okowuTUxRQWMietoCb0q7Mcab80R50kmsQnaDvZhM7udrSZtdli6A==
    username: AgCbiNp0QNI06hKlETmCEjGxQo7VGujyc5ocbz0KFiV0LfSfV0KTP9RJ7dPgnho3UK8+KALMyC/EKH4FzXdhpuppxN6O8aMXboHzhW1DUcWUpcXXpJchV1NprBDQdM9zr+6Y+tzdJpepBmGehFeLWQKB7WiyXFhKFVObp0w/CKfs86Pglr9PcBELY3zvtVPowO2PwSikVw4lixKgSL7UN0E7ymeYAq8kA/ApylSznkW5yDCX7Ipm8v5rbTlPVviIECfpmlebqAh9QvXJp7HaG8FnPGjvSYOq6Re0DTFSoIDSCE3JeiEtVHxpFKc6bJigh5hJN3R4SuRDrO2KJjJ0NCC+5INDHbaGkaaTPUsPHKrUFv9jP13etXkInG8WyzQ3dtaG0Pq/3KraiGZMkMcGTUdmObC9mIYHFlEKp1nmyLTNEVCz2X846NetjFWLEMzahKYXpcJfLZWlYeZCrU2whHOY82QYq7deG//9iQc5I83s3ed/8hYWdaWSMFvDwk/PAHQ+qdFqug6rjtnjYf5Qrf1aDQQuIZjpDV6qStVh49Wh5vX+pvO0dEVw0fcMzhlabo+IfU0/mDqhUBkGniCWJDJxaGLCMSuSFecytJdWDNecRk3FTG7/Ba12IHUWhwrruqocItkx6Xm1pymUdojaYTPPFn2EaPOm5vIakmE9euSMtqxvB8Fx0/L7rNu+7MvMVsWg47aWfw==
  template:
    metadata:
      name: keycloak-credentials
      namespace: keycloak-dev
