backend:
  livenessProbe:
    httpGet:
      path: /payment-paypal/actuator/health/liveness
  readinessProbe:
    httpGet:
      path: /payment-paypal/actuator/health/readiness
  image:
    repository: ghcr.io/23120091/payment-paypal
    tag: latest

  nameOverride: payment-paypal
  fullnameOverride: payment-paypal
  databaseName: payment-paypal
  ingress:
    enabled: false
  extraVolumes:
    - name: payment-paypal-application-config
      configMap:
        name: payment-paypal-application-configmap
  extraVolumeMounts:
    - name: payment-paypal-application-config
      mountPath: /opt/yas/payment-paypal
  extraApplicationConfigPaths:
    - /opt/yas/payment-paypal/payment-paypal-application.yaml